carbon-design-system/carbon-charts

.travis.yml

Remove old and unnecessary script from travis configs

Update travis deploy logic

---

CONTRIBUTING.md
README.md

- Add dev. environment instructions to CONTRIBUTING guideline
- Add semantic-versioning sticker to README

Update CONTRIBUTING & README guidelines

---

packages/core/src/base-chart.ts
packages/core/src/pie-chart.ts
packages/core/src/style.scss

Fixes #71
Disables both the hover effect and "click" pointer for unclickable legends.

Fix legendClickable option

---

.travis/after_success.sh
packages/react/index.js

- Fixes path for `build-packages-and-demos.sh`

Fix after_success.sh errors

---

packages/core/demo/index.scss
packages/core/src/base-chart.ts
packages/core/src/style.scss
packages/core/src/tools.ts
packages/react/src/base-chart.js

Closes #111 
- Add width & height props to **react** `BaseChart`
- Support width & height option values for `core` package

fix(react): Fix react wrappers resizing with animation

---

packages/react/src/index.js

Export DonutChart in the React package

---

packages/core/demo/index.html
packages/core/demo/index.scss
packages/core/src/base-chart.ts
packages/core/src/style.scss

- Add `chart-holder` class to chart holder element
- Add styling to make `position: relative` for chart holder
- Remove unused demo styling
Closes #125

fix(core): Fix tooltip positioning and clean up styling

---

package.json
packages/core/demo/demo-data/pie-donut.ts
packages/core/demo/index.ts
packages/core/src/donut-chart.ts

Allow custom donut center label & number

---

README.md

Add Netlify build status badge to README

---

packages/core/src/base-chart.ts

Remove updateSVG(), function is not used in latest versions.
Close #185. 
- list
- out
- updates
- [X ] Demos all features

fix(core): remove updateSVG()

---

packages/vue/src/ccv-donut-chart.vue
packages/vue/src/ccv-pie-chart.vue
packages/vue/stories/pie-donut-demo-data.js
packages/vue/stories/pie-donut.stories.js

- adds Vue.js wrapper and story for donut chart (basic and accessible)
- adds Vue.js wrapper and story for pie chart (basic and accessible)

Vue.js wrapper and story for the donut and pie chart component.

---

packages/react/package.json

https://github.com/carbon-design-system/carbon-charts/issues/216

Move react and react-dom to peerDependencies

---

.travis/after_success.sh
packages/vue/src/index.js
packages/vue/vue.config.js

- index.js for Vue wrappers has wrong context root
- eslint has problems locating config file when lerna creates symlinks (not fully understood) 
```
2:31:52 PM:  ERROR  Failed to compile with 1 errors14:31:52
2:31:52 PM: This relative module was not found:
2:31:52 PM: * ./components/ in ./src/index.js
```

Fix Vue build break

---

scripts/deploy.sh

fix(build): add npm credentials

---

README.md

- Update component status to reflect Vue progress
- Add CodeSandbox demo links

Update component status & demo links in README

---

packages/core/src/bar-chart.ts
packages/core/src/base-chart.ts
packages/core/src/components/index.ts
packages/core/src/components/overlay.ts
packages/core/src/configuration.ts
packages/core/src/pie-chart.ts
packages/core/src/scatter-chart.ts
packages/core/src/stacked-bar-chart.ts
packages/core/src/style.scss

- Move out overlays into a separate class `ChartOverlay`
- Support overlay states
- Stop render process if no data
Closes #262
**Customizable HTML contents:**

Show empty state when there is no data

---

.gitignore
packages/core/demo/chart-types.ts
packages/core/demo/demo-options.ts

In the previous PR some files were ignored accidentally. Adding those here.

feat(core): Color palettes

---

packages/react/package.json
packages/react/src/bar-chart.js
packages/react/src/base-chart.js
packages/react/src/donut-chart.js
packages/react/src/line-chart.js
packages/react/src/pie-chart.js

Updates:
- Update chart data if the `data` prop is updated
- Fix bug with charts shouting about width/height prop missing if they're passed-in through options
- Change `main` field in package.json to the bundle file for react
- Use `index.umd.js` in react components from `core`
Closes #289
Closes #284
Closes #283

fix(react): handle data updates from state, and fix errors with width/height props

---

packages/core/src/base-axis-chart.ts

-  added a resize observer for the gridline changes (due to updated data OR due to resize of chart/charting container or entire window).

Backdrop fix

---

CODEOWNERS

Since @theiliad and @natashadecoste are the actual maintainers 😀

chore(owners): update CODEOWNERS

---

packages/core/package.json
packages/core/src/base-chart.ts
packages/core/src/polyfills.ts
packages/core/src/styles/style.scss

- Change `main` package in core package.json to the regular ES bundle
- Add checks for the `window` variable in polyfills
- Fix legend cutoff and resizing issues

fix(core, react): fix react SSR & legend sizing issues

---

.travis.yml

perform gh-pages deploy only on the tagged commits

---

packages/angular/package.json
packages/core/package.json
packages/core/rollup.config.js
yarn.lock

Needed for ng-packager to work with angular 6+

fix(core): update typescript version to 2.8.1

---

packages/angular/package.json

fix(angular): update zone.js peerDependency range

---

packages/core/src/components/graphs/donut.ts
packages/core/src/components/graphs/pie.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/charts.ts

feat(core, angular, react, vue): allow customizations to pie labels & the donut center number

---

README.md

- update release notes link to point to changelog

docs(readme): update release notes link to point to changelog

---

packages/core/demo/index.html

fix(demos): add IBM Plex Sans Condensed to the demo sites

---

README.md

Add Scott Dickerson to the table

Update table of contributors

---

packages/core/demo/index.scss
packages/core/src/styles/components/_tooltip.scss

Add tooltip divider lines

---

packages/core/package.json

Make carbon-components a devDependency

---

packages/core/demo/index.html
packages/core/demo/index.scss

add deploys by netlify badge to core demo

---

packages/core/src/components/essentials/legend.ts
packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/components/graphs/bar-simple.ts
packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/components/graphs/line.ts
packages/core/src/components/graphs/pie.ts
packages/core/src/components/graphs/scatter.ts
packages/core/src/interfaces/events.ts
packages/core/src/model.ts

- dispatch event when legend items are changed (active status to disabled) by filtering
- event has all the data labels and their associated status (active: 1/true, disabled: 0/false)
closes #541

Legend filtering event

---

packages/core/src/tools.ts

- returning 1 sig fig for all labels

improvement(tools.ts): return 1 sig figure for pie/donut labels

---

packages/core/src/chart.ts
packages/core/src/components/essentials/legend.spec.ts
packages/core/src/components/essentials/title.spec.ts
packages/core/src/components/essentials/tooltip-bar.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/services/essentials/transitions.ts

updated any last listener events to use the enums

refactor(core): update tooltip and leftover events to enums

---

packages/core/src/components/graphs/line.ts

The PR optimizes the render logic of line graph to solve the issues with updating data.
Closes #585

fix line graph update issues

---

packages/core/src/components/graphs/pie.ts

Bbox notoriously breaks in Firefox

remove bbox dependency on pie labels

---

packages/core/src/interfaces/charts.ts

add missing option for scatter chart

fix scatter interface

---

packages/core/src/interfaces/charts.ts

Add missing option in donut interface

---

packages/core/demo/data/create-codesandbox.ts
packages/core/stories/tutorials.stories.ts
packages/core/stories/tutorials/getting-started/angular.ts
packages/core/stories/tutorials/getting-started/react.ts
packages/core/stories/tutorials/getting-started/vue.ts

add style import for angular

---

packages/core/src/components/graphs/scatter.ts

- simplifies render logic
- adds domain values as identifiers for each scatter circle

fix(core, angular, react, vue, svelte): fix scatter graph data updates

---

packages/core/src/components/graphs/gauge.ts

fix(core): fix gauge charts without a delta number

---

packages/core/demo/data/area.ts
packages/core/demo/data/index.ts
packages/core/src/model.ts

Fix stacked area chart with uneven data

---

packages/core/src/components/essentials/tooltip-bar.ts

Fix bar chart tooltip data

---

packages/core/demo/data/bar.ts
packages/core/src/services/scales-cartesian.ts

Remove primary and secondary options from demo

---

packages/core/src/components/essentials/legend.ts
packages/core/src/interfaces/a11y.ts

Add role fallback value for legend

---

packages/core/src/components/essentials/threshold.ts

fix(core, react, angular, vue, svelte): render both vertical and horizontal thresholds

---

packages/angular/package.json

chore(angular): allow zone.js versions of ^0.10.0

---

packages/core/src/components/axes/axis.ts
packages/core/src/components/axes/ruler.ts
packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/components/graphs/pie.ts

Improve accessibility with aria-labels

---

packages/core/src/components/graphs/pie.ts

Fix pie chart alignment

---

packages/core/src/components/axes/grid-brush.ts
packages/core/src/components/axes/zoom-bar.ts

Support zoom bar in mobile device by using touch event

Allow user to use zoom bar via mobile device browser

---

packages/core/src/components/essentials/tooltip.ts

fix(core): add aria-hidden attribute to tooltips

---

packages/core/CHANGELOG.md
packages/core/src/components/axes/axis.ts
packages/core/src/components/axes/ruler.ts
packages/core/src/components/essentials/legend.ts
packages/core/src/components/essentials/title-meter.ts
packages/core/src/components/essentials/tooltip-axis.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/components/graphs/area.ts
packages/core/src/components/graphs/gauge.ts
packages/core/src/components/graphs/meter.ts
packages/core/src/components/graphs/pie.ts
packages/core/src/components/graphs/scatter-stacked.ts
packages/core/src/components/graphs/scatter.ts
packages/core/src/components/graphs/skeleton.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/a11y.ts
packages/core/src/interfaces/components.ts
packages/core/src/model-meter.ts
packages/core/src/services/essentials/gradient-utils.ts
packages/vue/CHANGELOG.md

improvement(core): keyboard-navigatable legend items & accessibility fixes

---

packages/core/src/components/essentials/tooltip-axis.ts
packages/core/src/interfaces/components.ts

feat(core): allow custom labels for total & group in tooltips

---

packages/core/src/components/essentials/legend.ts
packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/components/graphs/bar-stacked.ts

fix(core): fix a11y issues with aria-labels & checkboxes

---

packages/core/src/services/essentials/dom-utils.ts
packages/core/src/styles/_chart-holder.scss

improvement(core): log an error to the console if CSS styles haven't been imported

---

packages/core/src/components/axes/zoom-bar.ts
packages/core/src/tools.ts

fix(core): replace import to lodash with lodash-es

---

packages/core/src/components/axes/two-dimensional-axes.ts

fix(core): correct axis title paddings in y-axes

---

packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/components/graphs/bar-stacked.ts

See demos. Bars now morph rather than fading away and fading back in

feat(core): smoother transitions in grouped and stacked bar charts

---

packages/core/src/interfaces/charts.ts

fix(core): add number to the donut center interface

---

packages/core/src/components/graphs/area-stacked.ts
packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/model.ts
packages/core/src/services/scales-cartesian.ts

fix(core): update stacked groups for stacked charts on data updates

---

packages/core/demo/data/index.ts
packages/core/demo/data/toolbar.ts
packages/core/src/components/axes/axis.ts

- sorts the demo groups in storybook
- removes the `experimental` flag from some demos

chore(demos): re-organize demos

---

packages/core/src/services/scales-cartesian.ts

fix(core): fix issues with zeroes in scale bounds

---

packages/core/demo/data/combo.ts
packages/core/demo/data/index.ts

docs(update demos): remove exp flag and re-add guage/lollipop demos

---

packages/core/CHANGELOG.md
packages/core/src/components/essentials/tooltip.ts
packages/react/CHANGELOG.md
packages/vue/CHANGELOG.md

```
export const comboData = [
{ group: 'Fulfilled', key: '2021-03-15T00:00:00', value: 0 },
{ group: 'Sent to node', key: '2021-03-15T00:00:00', value: 0 },
{ group: 'Fulfilled', key: '2021-03-15T01:00:00', value: 0 },
{ group: 'Sent to node', key: '2021-03-15T01:00:00', value: 0 },
{ group: 'Fulfilled', key: '2021-03-15T02:00:00', value: 0 },
{ group: 'Sent to node', key: '2021-03-15T02:00:00', value: 0 },
{ group: 'Fulfilled', key: '2021-03-15T03:00:00', value: 0 },
{ group: 'Sent to node', key: '2021-03-15T03:00:00', value: 0 },
{ group: 'Fulfilled', key: '2021-03-15T04:00:00', value: 0 },
{ group: 'Sent to node', key: '2021-03-15T04:00:00', value: 0 },
{ group: 'Fulfilled', key: '2021-03-15T05:00:00', value: 0 },
{ group: 'Sent to node', key: '2021-03-15T05:00:00', value: 0 },
{ …
```

fix(tooltip): tooltip discarding 0 values

---

packages/angular/.storybook/config.js
packages/angular/stories/all.stories.ts
packages/core/demo/data/CHART_TYPES.ts
packages/core/demo/data/area.ts
packages/core/demo/data/bar.ts
packages/core/demo/data/boxplot.ts
packages/core/demo/data/combo.ts
packages/core/demo/data/index.ts
packages/core/demo/data/line.ts
packages/core/demo/data/scatter.ts
packages/core/demo/styles.scss
packages/core/src/model.ts
packages/core/src/tools.ts
packages/core/stories/all.stories.ts
packages/core/stories/tutorials.stories.ts
packages/react/.storybook/config.js
packages/react/stories/all.stories.js
packages/svelte/.storybook/config.js
packages/svelte/src/BaseChart.svelte
packages/svelte/stories/all.stories.js
packages/vue/.storybook/config.js
packages/vue/stories/all.stories.js

- Move all demos into 4 categories
- Update all storybooks

Demos reorg

---

packages/core/demo/data/area.ts
packages/core/demo/data/index.ts

Separates out area demos into `simple` & `stacked`

docs(demos): separate out area demos

---

packages/core/src/components/graphs/wordcloud.ts
packages/core/src/interfaces/charts.ts

fix(wordcloud): fix render issues in firefox & add getFillColor()

---

packages/core/CHANGELOG.md
packages/core/demo/data/area.ts
packages/core/demo/data/index.ts
packages/core/demo/data/line.ts
packages/core/src/components/essentials/legend.ts
packages/core/src/tools.ts
packages/react/CHANGELOG.md
packages/react/stories/all.stories.js
packages/vue/CHANGELOG.md
packages/vue/stories/all.stories.js

closes #995 
vertical legends should render properly + demo for vertical + left position legend

fix(legend): vertical alignment

---

packages/core/stories/tutorials/event-listeners.ts

docs(demos): add code examples in the event listeners tutorial

---

packages/core/demo/data/index.ts
packages/core/src/components/graphs/circle-pack.ts
packages/core/src/styles/graphs/_circle-pack.scss

Update circle pack cursor styling

---

packages/core/src/components/essentials/tooltip.ts

fix(core): make sure tooltips are properly positioned when closer to the edges

---

packages/core/src/services/scales-cartesian.ts

fix(core): account for threshold values when determining scale domains

---

packages/core/src/components/graphs/radar.ts

1. Stops axes from updating when using the radar legend
2. Optimizes rendering logic and animations in radar
3. Zooming animation is minimized and more controlled

fix(core): radar animation issues, axis updates and zooming

---

packages/core/src/components/graphs/bar-simple.ts

fix(core): start bars at correct position when axis min is non-zero

---

packages/angular/stories/diagrams/0_diagram.stories.ts
packages/core/demo/styles.scss
packages/react/stories/diagrams/0_Diagrams.stories.js

1. Update notes on desktop-only experiences
2. Update styling for desktop-only demos
3. Add react example in the angular story (for now)

Update diagram examples

---

packages/core/src/components/graphs/radar.ts

fix #1053
- list
- out
- updates

fix(core): correctly display negative values

---

packages/core/src/interfaces/events.ts

fix(core): update area chart event enums to use the scatter enums

---

packages/core/package.json

- add dom-to-image as a dependency

build(core): add dom-to-image as a dependency

---

packages/core/src/configuration.ts

fix(core): make sure document exists in case using SSR

---

CHANGELOG.md

This is just to test the new release workflow

trigger release

---

packages/core/src/styles/components/_modal.scss

update modal z-index

---

.github/workflows/release.yml
lerna.json

Trigger release on any pushes to master unless commit message starts with `skip-release`

Update release workflow 2

---

packages/svelte/README.md

Closes #1088 
- docs(svelte): update sveltekit configuration instructions
- docs(svelte): use reactive statement in events example
- docs(svelte): capitalize names of svelte libraries/frameworks

docs(svelte): update sveltekit configuration instructions

---

packages/core/src/services/essentials/dom-utils.ts

Adds:
- checks to make sure that exiting functionality is available
- keeps track of `fullscreenchange` on document

fix(core): optimize fullscreen logic

---

packages/core/demo/create-codesandbox.ts

just a tiny change for our sandboxes

docs(codesandbox): update d3 version to 7.0.0

---

packages/core/demo/create-codesandbox.ts

docs(all): update d3 version in sandbox demos

---

packages/angular/src/diagrams/card-node/card-node.component.ts
packages/angular/src/diagrams/shape-node/shape-node.component.ts
packages/angular/stories/diagrams/0_diagram.stories.ts
packages/angular/stories/diagrams/shape-node.stories.ts
packages/core/src/styles/components/diagrams/_edge.scss
packages/react/src/diagrams/CardNode/CardNode.tsx
packages/react/src/diagrams/ShapeNode/ShapeNode.tsx
packages/react/stories/diagrams/0_Diagrams.stories.js
packages/react/stories/diagrams/ShapeNode.stories.js

Safari is weird with `stroke-dasharray` & elements without an explicit `position` definition where translations are used...
This aims to solve that for our demos & components that we ship out.

fix(core): diagram rendering issues in safari

---

packages/core/src/components/essentials/legend.ts
packages/core/src/styles/components/_legend.scss

fix(core): legend alignment incorrect initial rendering

---

packages/core/src/components/essentials/tooltip.ts

- replace empty hyperlink with `div` tag.
fix #952

fix(core): replace empty hyperlink with an appropriate tag

---

packages/core/demo/data/area.ts
packages/core/demo/data/hightlight.ts
packages/core/demo/data/index.ts

- Fix broken demo in zoombar
- There was circular dependencies

docs(core): fix broken demo

---

packages/core/src/components/axes/toolbar.ts
packages/core/src/components/essentials/legend.ts
packages/core/src/components/essentials/modal.ts

fix #1204
- Keyboard Arrow Left & Right for navigating toolbar
- Keyboard Arrow Up and Down for navigating overflow menu
- Fixed keyboard event for opening/closing modal
- Legend checkboxes enable with space keyboard event instead of enter
- Legend item focus triggers hover event

fix(core): improve keyboard accessibility

---

packages/angular/src/diagrams/card-node/card-node-column.component.ts
packages/core/src/chart.ts
packages/core/src/charts/combo.ts
packages/core/src/components/component.ts
packages/core/src/components/essentials/modal.ts
packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/services/essentials/files.ts
packages/core/src/services/service.ts

Just working through some of the reported violations

fix(monorepo): some violations reported by sonarcloud

---

packages/svelte/README.md

The docs update in https://github.com/carbon-design-system/carbon-charts/pull/1266 is incorrect. This PR fixes and updates the Svelte + Rollup guidance.
The [carbon-charts-svelte-examples/rollup](https://github.com/metonym/carbon-charts-svelte-examples/blob/ae73a0d9cdde32d8aa2075a1808f154d2bc83e0f/rollup/rollup.config.js) example has also been updated.
- docs: `this` has been rewritten to `undefined` error is solved by adding "context: 'window'" to rollup.config.js
- docs: `inlineDynamicImports: true` is necessary if dynamically importing code to enable code-splitting
- docs: add guidance on ignoring select circular dependency warnings

docs(svelte): fix and update Rollup usage

---

packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/components/graphs/bar.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/components.ts

improvement(bars): add `spacingFactor` option

---

packages/core/src/components/graphs/treemap.ts
packages/core/src/model/treemap.ts

Updates:
- Removes the `total` calculation in treemap, we seem to be not using it!
- Fix tabular representation for elements with no children

fix(treemap): issues with having a depth of 1

---

packages/core/src/components/axes/toolbar.ts
packages/core/src/components/essentials/modal.ts

Needed for https://github.com/carbon-design-system/carbon-website/pull/2764

feat(core): add v11 classnames to modal & overflow menu

---

packages/react/package.json
packages/react/src/alluvial-chart.tsx
packages/react/src/area-chart-stacked.tsx
packages/react/src/area-chart.tsx
packages/react/src/bar-chart-grouped.tsx
packages/react/src/bar-chart-simple.tsx
packages/react/src/bar-chart-stacked.tsx
packages/react/src/boxplot-chart.tsx
packages/react/src/bubble-chart.tsx
packages/react/src/bullet-chart.tsx
packages/react/src/circle-pack-chart.tsx
packages/react/src/combo-chart.tsx
packages/react/src/donut-chart.tsx
packages/react/src/gauge-chart.tsx
packages/react/src/heatmap-chart.tsx
packages/react/src/histogram-chart.tsx
packages/react/src/line-chart.tsx
packages/react/src/lollipop-chart.tsx
packages/react/src/meter-chart.tsx
packages/react/src/pie-chart.tsx
packages/react/src/radar-chart.tsx
packages/react/src/scatter-chart.tsx
packages/react/src/tree-chart.tsx
packages/react/src/treemap-chart.tsx
packages/react/src/utils.ts
packages/react/src/wordcloud-chart.tsx

feat(react): add react 18 as peerDep, update componentDidMount logic for StrictMode

---

packages/angular/carbon.yml
packages/core/carbon.yml
packages/react/carbon.yml
packages/svelte/carbon.yml
packages/vue/carbon.yml

- Update library descriptions per design spec: https://airtable.com/shrdwElZNyJdGtZkS/tblE2Y75BfY0Z0T2O
- Added "Vanilla" to a library name
- Fixed broken SVG path
Updated name and descriptions:
Histogram thumbnail isn't broken:

docs: update library descriptions

---

packages/core/src/components/axes/toolbar.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/components/graphs/alluvial.ts
packages/core/src/styles/components/_tooltip.scss

fix(csp): remove inline styles

---

package.json

Make package.json agree with .nvmrc so yarn is aware
lerna success run Ran npm script 'demo:build' in 5 packages in 65.3s:
lerna success - @carbon/charts-angular
lerna success - @carbon/charts
lerna success - @carbon/charts-react
lerna success - @carbon/charts-svelte
lerna success - @carbon/charts-vue
lerna notice cli v3.20.2
lerna info Executing command in 5 packages: "$LERNA_ROOT_PATH/scripts/copy-demos-to-deploy-dir.sh"
lerna success exec Executed command in 5 packages: "$LERNA_ROOT_PATH/scripts/copy-demos-to-deploy-dir.sh"
✨  Done in 101.62s.

match node engine to nvmrc

---

.yarnrc.yml
lerna.json
netlify.toml
package.json
yarn.lock

- Upgraded lerna to 6.6.1
- Added options to lerna.json
- Added yarn config setting required by Netlify
- Changed Netlify env to use Python 2.7 which is required in order to build node-sass for Angular < 12

chore(app): lerna 6.6.1 support

---

packages/core/src/components/axes/chart-clip.ts
packages/core/src/components/axes/grid-brush.ts
packages/core/src/components/essentials/title-meter.ts
packages/core/src/components/graphs/radar.ts

Fixes 3 of 4 issues in https://github.com/carbon-design-system/carbon-charts/issues/1555.
Radar chart with missing data points still generates paths with NaN in them.

fix(1555): corrects JS console errors for all but radar chart

---

SECURITY.md

skip-release - SECURITY.md

---

.github/workflows/release.yml
README.md
lerna.json
packages/angular/README.md
packages/angular/src/stories/all.stories.ts
packages/core/README.md
packages/core/src/stories/all.stories.ts
packages/react/README.md
packages/react/src/stories/1-charts.stories.tsx
packages/svelte/src/stories/ChartWrapper.svelte
packages/vue/README.md
packages/vue/src/stories/all.stories.ts
scripts/deploy.sh
scripts/next.sh

- Fixes broken links in stories and Read Me files
- Removes redundant items from deploy.sh

fix(links, deploy cleanup)

---

packages/angular/README.md
packages/core/README.md
packages/core/scss/demos.scss
packages/core/src/demo/charts/index.ts
packages/core/src/stories/getting-started/react.stories.mdx
packages/core/src/stories/getting-started/svelte.stories.mdx
packages/react/README.md
packages/react/src/stories/react.stories.mdx
packages/svelte/src/stories/svelte.stories.mdx
packages/vue/README.md

- Fix Storybook Welcome CSS - changed text to white
- Fixed more URLs in README.md and MDX files

fix(storybook welcome css, hyperlinks in mdx and readme files)

---

packages/core/src/model/model.ts
packages/core/src/services/scales-cartesian.ts

- https://github.com/carbon-design-system/carbon-charts/issues/1528
- Histogram charts are now able to display negative values in x-axis

fix(model-scalesCartesian):Histogram unable to show negative values on x-axis

---

packages/core/src/components/axes/toolbar.ts

- https://github.com/carbon-design-system/carbon-charts/issues/1724
- Addition of role for toolbar buttons

fix(toolbar):Added role for toolbar buttons

---

packages/core/src/components/graphs/donut.ts
packages/core/src/configuration.ts

- https://github.com/carbon-design-system/carbon-charts/issues/1762
- Added numberFormatter for donut chart options

fix(donut):Added numberFormatter for donut options

---

packages/angular/.storybook/manager-head.html
packages/core/.storybook/manager-head.html
packages/core/scss/demos.scss
packages/react/.storybook/manager-head.html
packages/svelte/.storybook/manager-head.html
packages/vue/.storybook/manager-head.html

add commonjs privacy policy/footer, and analytics

---

packages/angular/package.json
packages/angular/telemetry.yml
packages/core/package.json
packages/core/telemetry.yml
packages/react/package.json
packages/react/telemetry.yml
packages/svelte/package.json
packages/svelte/telemetry.yml
packages/vue/package.json
packages/vue/telemetry.yml
yarn.lock

***@carbon/charts-angular***
- Update `@ibm/telemetry-js` version to 1.5.1
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to `telemetry.yml`
***@carbon/charts***
- Update `@ibm/telemetry-js` version to 1.5.1
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to `telemetry.yml`
***@carbon/charts-react***
- Update `@ibm/telemetry-js` version to 1.5.1
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to `telemetry.yml`
***@carbon/charts-svelte***
- Update `@ibm/telemetry-js` version to 1.5.1
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope)  config to …

feat(telemetry): instrument charts packages with JS scope

---

packages/svelte/src/lib/AlluvialChart.svelte
packages/svelte/src/lib/AreaChart.svelte
packages/svelte/src/lib/BarChartGrouped.svelte
packages/svelte/src/lib/BarChartSimple.svelte
packages/svelte/src/lib/BarChartStacked.svelte
packages/svelte/src/lib/BoxplotChart.svelte
packages/svelte/src/lib/BubbleChart.svelte
packages/svelte/src/lib/BulletChart.svelte
packages/svelte/src/lib/ChoroplethChart.svelte
packages/svelte/src/lib/CirclePackChart.svelte
packages/svelte/src/lib/ComboChart.svelte
packages/svelte/src/lib/DonutChart.svelte
packages/svelte/src/lib/GaugeChart.svelte
packages/svelte/src/lib/HeatmapChart.svelte
packages/svelte/src/lib/HistogramChart.svelte
packages/svelte/src/lib/LineChart.svelte
packages/svelte/src/lib/LollipopChart.svelte
packages/svelte/src/lib/MeterChart.svelte
packages/svelte/src/lib/PieChart.svelte
packages/svelte/src/lib/RadarChart.svelte
packages/svelte/src/lib/ScatterChart.svelte
packages/svelte/src/lib/StackedAreaChart.svelte
packages/svelte/src/lib/TreeChart.svelte
packages/svelte/src/lib/TreemapChart.svelte
packages/svelte/src/lib/WordCloudChart.svelte

fixes https://github.com/carbon-design-system/carbon-charts/issues/1842

[Regression]: Make `data` and `ref` props optional in Svelte components

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yaml
packages/core/src/components/graphs/gauge.ts
packages/core/src/components/graphs/heatmap.ts
packages/core/src/components/graphs/radar.ts
packages/core/src/selectedGroups.spec.ts

- Closes https://github.com/carbon-design-system/carbon-charts/issues/1850

fix(1850): redefined variables violated no-shadow rule

---

packages/core/src/components/axes/toolbar.ts

fix(toolbar): remove aria-label as it's not readable

---

packages/angular/README.md
packages/angular/telemetry.yml
packages/core/README.md
packages/core/telemetry.yml
packages/react/README.md
packages/react/telemetry.yml
packages/svelte/README.md
packages/svelte/telemetry.yml
packages/vue/README.md
packages/vue/telemetry.yml

This PR updates the endpoint within each package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.
- telemetry.yml endpoint to new stable endpoint
- updated wording under telemetry notice in each README
N/A

chore(telemetry): update endpoint for main

---

packages/core/src/interfaces/components.ts

Fix optional type definitions for toolbar and tabularRep in Locale.translations
no visual changes

Fix components.ts

---

packages/core/src/components/component.ts
packages/core/src/components/graphs/line.ts
packages/docs/src/lib/area/examplesStacked.ts

Closes #2002
Closes #1989
Closes #1996

fix(Line graph): zoom issues in firefox

---

packages/core/src/components/axes/toolbar.ts

fix(Toolbar): add `type=button` to buttons

---

packages/core/src/components/axes/grid-brush.ts
packages/core/src/components/axes/zoom-bar.ts
packages/core/src/services/zoom.ts

feat(Events.ZoomDomain.CHANGE): add type ('in' | 'out' | 'reset' | 'manual')

---

packages/core/src/components/axes/axis.ts
packages/core/src/components/axes/two-dimensional-axes.ts
packages/core/src/components/layout/layout.ts
packages/core/src/configuration.ts

fix(Layout): elements sticking out of wrappers

---

packages/core/src/components/axes/ruler-binned.ts
packages/core/src/components/essentials/tooltip-axis.ts
packages/core/src/interfaces/components.ts
packages/docs/src/lib/area/examplesStacked.ts

feat(Tooltip): add customTotalCalculation function
