carbon-design-system/carbon-charts

CONTRIBUTING.md
README.md

- Add codesandbox demo link
- Remove unnecessary content

chore(monorepo): Update README content

---

packages/core/demo/demo-data/pie-donut.ts
packages/core/demo/index.ts
packages/core/src/donut-chart.ts

- By default the sum of values will be shown within the DonutCenter component
Closes #83

Calculate sum of values for DonutCenter automatically

---

packages/core/src/configuration.ts
packages/react/package.json

- Optimize colors since transparency makes them look unsaturated, similar to CMYK colors
- Remove `react-icons` from the React package

chore(core): Optimize threshold colors, remove react-icons as a dependency

---

packages/core/src/configuration.ts
packages/core/src/line-chart.ts
packages/core/src/stacked-bar-chart.ts

Fix bug #89 
Files updated: 
- core/configuration.ts: updated line chart tooltip fix. 
- core/stacked-bar-chart.ts: updated addDataPointEventListener
- core/line-chart.ts: updated addDataPointEventListener
- list
- out
- updates

Tooltips Bug Fix #89

---

packages/angular/package.json
scripts/build-packages-and-demos.sh

Build seems to be broken because Travis is not able to find `@angular/compiler` inside of `ng-packager`, this PR will add it as a dev-dependency to the `charts-angular` package.

Fix angular build on Travis

---

packages/core/demo/demo-data/line.ts
packages/core/src/line-chart.ts
packages/core/src/services/curves.ts

Adds support for D3 curve modification methods like tension, alpha and
beta. Re-done because of the broken Git forks.
Closes #39
- Adds in support for all D3 curve modifying methods (`.tension()`, `.alpha()`, `.beta()`, any any other similar methods).
The demo `curveNatural` has been replaced with the `curveCardinal` with a modified tension (it is visually identical.)

feat($core): adds support for tension, beta, alpha in curves

---

packages/core/demo/index.ts

Minor bugfix.
Essentially the URL the experimental switch redirects to is incorrect, and this fixes it by factoring in `location.pathname`.

fix(core demo): Fix experimental link issue

---

packages/core/src/bar-chart.ts
packages/core/src/base-axis-chart.ts

- Rename class for threshold bars
- Only trigger showing of tooltip for `rect`s that have a class of `bar`
Closes #134

fix(core): Fix interference of thresholds and bar chart elements

---

packages/core/demo/demo-data/bar.ts
packages/core/src/bar-chart.ts
packages/core/src/configuration.ts
packages/core/src/stacked-bar-chart.ts
packages/core/src/tools.ts

closes #139 
closes #140 
Right now it's just applied to normal bars, but the process should be the same for stacked bars.
Grouped bars will be a bit of a different beast - I'm not sure this entirely applies to them anyway.

feat(bar): bar chart should support a max bar width

---

packages/core/src/style.scss

Currently `text-align` isn't enforced in the CSS for the legend popup, and in cases where your container does `text-align: center` you'll see this:
Closes #168

fix(core): Enforce text alignment of legend popup in the styles

---

.travis.yml
package.json
packages/core/package.json
packages/core/src/assets/patterns/index.ts
packages/core/src/assets/patterns/pattern-1.ts
packages/core/src/assets/patterns/pattern-10.ts
packages/core/src/assets/patterns/pattern-11.ts
packages/core/src/assets/patterns/pattern-2.ts
packages/core/src/assets/patterns/pattern-3.ts
packages/core/src/assets/patterns/pattern-4.ts
packages/core/src/assets/patterns/pattern-5.ts
packages/core/src/assets/patterns/pattern-6.ts
packages/core/src/assets/patterns/pattern-7.ts
packages/core/src/assets/patterns/pattern-8.ts
packages/core/src/assets/patterns/pattern-9.ts
packages/core/src/services/patterns.ts
packages/vue/package.json

- export patterns as strings in ts files (simplifies distribution, potentially simplifies adding patterns in the future)
- add d3@4 as a hard dep
- remove `after_success` from travis.yml ... it's not needed at this point

fix(core): export patterns as strings of svgs

---

packages/vue/package.json
packages/vue/src/index.js

- Set `main` for package correctly
- Export \src and \dist to package, so that individual components can be imported by clients (like the React wrappers do).
Note: the vue-cli library build generates and extraneous dist/demo.html that does not work. There is an issue for this here: https://github.com/vuejs/vue-cli/issues/3291

Fix Vue wrapper packaging issue

---

packages/core/index.umd.js
packages/core/package.json
packages/react/src/bar-chart.js
packages/react/src/donut-chart.js
packages/react/src/line-chart.js
packages/react/src/pie-chart.js

Updates:
- Change `main` file in `package.json` to `index.umd.js`
- Update react imports to just consume `@carbon/charts`

fix(react core): change main bundle to umd in core, and update imports in react

---

packages/core/demo/demo-data/bar.ts
packages/core/demo/demo-data/combo.ts
packages/core/demo/demo-data/line.ts
packages/core/demo/demo-data/pie-donut.ts

- remove demo titles until refactor layout
- titles can be used on charts if the chart is a big enough size that it looks good, otherwise chart title can be separate to the chart (until refactor)

remove  titles from the demo

---

packages/react/src/base-chart.js

- Fixes componentDidUpdate method in base chart to use current props instead of previous props. https://reactjs.org/docs/react-component.html#componentdidupdate

[React] Fix componentDidUpdate to use current props.

---

packages/core/demo/chart-types.ts
packages/core/demo/demo-data/line.ts

The current scatter time-series demo is showing the discrete version by mistake.

chore(core): fix scatter time series demo

---

packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/components/graphs/pie.ts

Updated grouped bar and donut/pie to handle objects passed in as data instead of just an array of data as numbers. This helps the data layer to be more universal across the different charts
before it had to **only** be of the type : 
```
data: [
32432,
21312,
56456,
21312,
34234
]
```
but now it can handle this as well: 
```
data: [
{
date: new Date(2019, 0, 1),
value: 65000,
},
{
date: new Date(2019, 0, 2),
value: 29123
},
{
date: new Date(2019, 0, 3),
value: 35213
}
]
```

refactor(core): update the data handling 

---

packages/core/src/styles/graphs/_line.scss
packages/core/src/styles/graphs/_scatter.scss

Closes #433
change the line weights to be 1.5 and node outlines to match.

style(core): line chart node styles

---

packages/core/src/interfaces/components.ts

Tooltip interface was updated to reflect the naming change within tooltip (tooltip looks for a
valueFormatter, instead of formatter). Name was updated to be more clear with the addition of
supporting completely custom tooltips as well as allowing users to intercept and modify just the
value (appending %, $, localizing, etc).
- fixed a missed occurance of the name change for the tooltip valueFormatter
the demo code for testing/using a value formatter:
```
export const lineTimeSeriesOptions = {
title: "Line (time series)",
axes: {
left: {
secondary: true
},
bottom: {
scaleType: "time",
primary: true
}
},
curve: "curveMonotoneX",
tooltip: {
valueFormatter: (d) => { return `${d}%`;}
}
};
```

fix(core): update tooltip value formatter

---

packages/core/src/styles/components/_grid.scss

Closes #432
- updated white/g10 to use same color as backdrop (white)
- updated the color used on g100 backdrops to being gray100 (same as g90)

style(core): restyle chart backdrop colors (theming)

---

packages/core/src/styles/components/_grid.scss

- added a border to the backdrop 
- the active axis lines are still on with a darker stroke that the gridlines and border

style(core): outline the chart grid with a border

---

packages/core/src/tools.spec.ts
packages/core/src/tools.ts

Hi, this is Accurat :)
While making an unrelated PR (#299), we found out that `Tools.getProperty()` did return `null` for falsy values.
We are proposing this fix to make it return the actual value in the object – even when `false` or `0` or `""`.
In practice, we haven't found an existing example of this bug in the current codebase, but this is an obstacle in creating any `true`-defaulted property.
We are creating this mini-PR to be extra sure this pretty global change does not break anything. The problem could arise if some code relies on the bug, being the function used ~60 times across the codebase.
Some simple tests were added to make the problem appear.
Feel free to close this directly if we made a wrong assumption, or if it's by design.
- Added tests which are failing when the bug is …

fix(core): Tools.getProperty did return 'null' for falsy values

---

packages/core/src/services/scales-cartesian.ts
packages/core/tsconfig.json

- add `esModuleInterop: true` flag in `tsconfig.json` to fix json import

Fix locale json import 

---

packages/core/demo/demo-data/bar.ts
packages/core/demo/demo-data/index.ts
packages/core/src/interfaces/axis-scales.ts
packages/core/src/services/scales-cartesian.ts

Partially solves #402 by allowing to specify a fixed domain through each axis configuration.
The keyword `domain` has been added to `AxisOptions` interface. If you prefer, we can change it to something more inline with your naming conventions (maybe something like `extents` would be better?)

optional domain setting

---

packages/core/src/services/essentials/dom-utils.ts

added a bit of validation to ensure the best possible dimensions returned for element
solves the issue of incorrect sizing when hiding and showing the chart back-to-back

Fix function that calculates size of SVG DOM elements

---

packages/core/src/charts/bar-grouped.ts
packages/core/src/charts/bar-simple.ts
packages/core/src/charts/bar-stacked.ts
packages/core/src/charts/bubble.ts
packages/core/src/charts/donut.ts
packages/core/src/charts/line.ts
packages/core/src/charts/pie.ts
packages/core/src/charts/scatter.ts
packages/core/src/components/axes/two-dimensional-axes.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/axis-scales.ts
packages/core/src/services/scales-cartesian.ts
packages/core/src/tools.spec.ts
packages/core/src/tools.ts

Closes #402.
Add configuration option `includeZero?: boolean` (default true) to let users exclude 0 from the axis. 
`includeZero: true` (default behaviour)
`includeZero: false`

feat(core): Add configuration option to not include 0 on axes

---

packages/core/src/components/axes/axis.ts
packages/core/src/interfaces/events.ts

Closes #487
I'm wondering if we should distinguish axis events based on axis position (e.g. `left`, `right` etc.)

add mouse events for axis labels

---

packages/core/demo/demo-data/index.ts
packages/core/demo/demo-data/line.ts
packages/core/src/components/axes/axis.ts

Closes: #519.
As is:
After this PR:

Timeseries axis: Fix rotating tick when is not necessary

---

packages/core/tslint.json

Add two simple _tslint_ rules:
- `space-before-function-paren`: disallows a space before function parenthesis
- `trailing-comma`: disallows trailing commas.

Tslint: Add rules about trailing comma and space before function parenthesis

---

packages/core/src/components/component.ts
packages/core/src/components/essentials/legend.spec.ts
packages/core/src/components/essentials/title.spec.ts
packages/core/src/components/essentials/tooltip-bar.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/services/essentials/dom-utils.ts
packages/core/src/tests/tools.ts

fix #546
- update the import path for settings from carbon-components

fix(core): update import path carbon-components

---

packages/core/src/components/graphs/bar-stacked.ts

- Fixes a bug where 0 value bars wouldn't render in the stacked bar chart causing the bars to shift left.

fix(bar-stacked): render 0 value bars

---

packages/core/demo/data/pie.ts
packages/core/src/components/graphs/pie.ts

- updated to remove label data for slices that are 0, label `text` and callouts won't get rendered to the DOM
closes #500 
closes #552 
last dataset value is set to 0, it does not render the label and the next smallest slice (under the threshold) will become the "right" callout. 
with last dataset value set to 0 **and** there are 2 other dataset values that are within the threshold (they become left/right callout).

Pie zero labels

---

packages/core/src/components/graphs/bar-stacked.ts

When stacked bar tooltips are shown, the tooltip doesn't get passed the full datapoint object, rather a minimal version of it (because of how stacked data gets generated in D3).
This PR will find the corresponding data point and pass it in full to tooltips.

provide all datapoint info to stacked bar tooltips

---

packages/core/src/components/axes/axis.ts

Currently axis tick formatters are only being called for linear scales.
This PR adds support for all scale types as long as a formatter is provided by the user.

optimize axis tick formatting

---

packages/core/demo/data/index.ts
packages/core/demo/data/line.ts
packages/core/src/components/graphs/line.ts
packages/core/src/components/graphs/scatter.ts
packages/core/src/services/scales-cartesian.ts
packages/core/src/tools.ts

Support for Horizontal Line and Scatter Chart.
Resolve #583.

Support for Horizontal Line and Scatter Chart

---

packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/model.ts
packages/core/src/services/scales-cartesian.ts

This PR solves some linting problems due to the arrangement of methods that did not respect with the following TSlint rule:
```json
"member-ordering": [
true,
{
"order": [
"public-static-field",
"protected-static-field",
"private-static-field",
"public-static-method",
"protected-static-method",
"private-static-method",
"public-instance-field",
"protected-instance-field",
"private-instance-field",
"public-constructor",
"protected-constructor",
"private-constructor",
"public-instance-method",
"protected-instance-method",
"private-instance-method"
]
}
]
```
@caesarsol

Fix linting problem about methods order

---

packages/vue/src/ccv-base-chart.vue

Currently we're supporting the new tabular format (array-type) as well as the old object-based structure. We'll need to add this for now for Vue to allow both types, and in the future we'll only allow Arrays

fix vue type check for charting data

---

packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/components/graphs/bar-simple.ts
packages/core/src/components/graphs/bar-stacked.ts

This fixes the bars color getting darker and darker until black, that @theiliad found during yesterday's call.
Since we removed the Ruler from the Combo chart the bug is not visible anywhere, but this was the root cause and we feel it's cleaner in this way.

Fix hover color logics for Bars hover

---

packages/core/src/styles/components/_axis.scss

currently they're showing up with an opacity of 0, which would leave pointer-events enabled for them, so I added `visibility: hidden;`

hide invisible axes components

---

packages/core/src/components/axes/axis.ts

Axis labels rotate in the incorrect direction as per the specs.
Closes #532

Fix axis rotation angle

---

packages/core/src/components/essentials/threshold.ts
packages/svelte/build.sh
packages/svelte/rollup.config.js
packages/svelte/src/BaseChart.svelte

**Description**
Currently, Svelte demos do not work in CodeSandbox.
This is caused because the `bind:this` directive used in [BaseChart.svelte](https://github.com/carbon-design-system/carbon-charts/blob/master/packages/svelte/src/BaseChart.svelte#L30) component is never defined. As a result, the chart does not mount to the DOM. This issue is [well documented](https://github.com/sveltejs/svelte/issues/2937).
However, this problem only occurs in the UMD and ESM build formats and if `svelte` cannot be de-duplicated in a Rollup/webpack set-up. Uncompiled Svelte source code works properly; the `bind:` directive works properly and `ref` grabs a reference to the div element.
CodeSandbox likely uses either the UMD (`main`) or ESM (`module`) package entries. For a typical Rollup or webpack set-up …

fix(svelte): support Svelte CodeSandbox demos

---

packages/core/src/interfaces/charts.ts

- #668 - add missing `timescale` option in `AxisOptions` interface

fix: add missing timescale option in AxisOptions interface

---

packages/core/src/charts/gauge.ts

I noticed that tooltip was never added in with the gauge chart, it is needed for title truncation

fix(core): add tooltip to gauge chart

---

packages/svelte/src/GaugeChart.svelte
packages/svelte/src/index.js

- add Gauge chart wrapper for Svelte
Verify the Gauge charts in the Storybook by running `yarn storybook`.
Verify the Svelte library can build by running `yarn build`.

feat(svelte): add Gauge chart wrapper

---

packages/core/src/services/essentials/dom-utils.ts

We need to temporarily take out this element and think of a better solution for having text alternatives for charts. When we add the `<title>` element we end up seeing a browser tooltip constantly when hovering on the chart

Remove <title> element

---

packages/core/src/components/axes/axis.ts

The d3 scale.nice() function changes the scale domain.
In some cases, this domain change will cause obvious extra space in addition to the space created by `addSpaceOnEdges` option.
Example data:
```
[
{
"group": "dataset 1",
"date": "2020-07-14T02:07:00.000Z",
"value": 3
},
{
"group": "dataset 1",
"date": "2020-07-14T18:07:01.538Z",
"value": 7
},
{
"group": "dataset 1",
"date": "2020-07-15T10:07:03.076Z",
"value": 14
},
{
"group": "dataset 1",
"date": "2020-07-16T02:07:04.614Z",
"value": 0
},
{
"group": "dataset 1",
"date": "2020-07-16T18:07:06.152Z",
"value": 3
},
{
"group": "dataset 1",
"date": "2020-07-17T10:07:07.690Z",
"value": 3
},
{
"group": "dataset 1",
"date": "2020-07-18T02:07:09.228Z",
"value": 0
},
{
"group": "dataset 1",
"date": "2020-07-18T18:07:10.766Z",
"value": 8
},
{ …
```

Avoid extra space between graphs and chart edge

---

packages/core/src/components/essentials/tooltip.ts

- Fix the wrong ruler tooltip y position with zoom bar enabled
- Add zoom bar height to tooltip y position if zoom bar is enabled
before:
after:

fix: fix tooltip position with zoom bar enabled

---

packages/core/src/components/axes/zoom-bar.ts

.join() could causes some problems in typescript project.
Use enter().append() instead.

fix: use enter().append() instead of join()

---

packages/svelte/src/MeterChart.svelte
packages/svelte/src/index.js

- add Meter chart wrapper for Svelte
Run the storybook:

feat(svelte): add Meter chart wrapper

---

packages/core/CHANGELOG.md
packages/core/demo/data/index.ts
packages/core/src/components/axes/axis.ts
packages/core/src/components/axes/grid.ts
packages/core/src/components/essentials/legend.ts
packages/core/src/components/essentials/title-meter.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/components/graphs/pie.ts
packages/core/src/components/graphs/radar.ts
packages/core/src/configuration-non-customizable.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/charts.ts
packages/core/src/interfaces/components.ts
packages/core/src/interfaces/enums.ts
packages/core/src/model.ts
packages/vue/CHANGELOG.md

This had been long overdue. I've separated out anything that shouldn't be customized into a separate `configuration-non-customizables.ts` file

fix(core): separate out non-customizables in configuration.ts

---

packages/core/src/components/axes/zoom-bar.ts

Since the tooltip for zoom bar handle was cancelled, it makes more sense to change the zoom bar handle cursor from pointer to ew-resize.

feat: change zoom bar handle cursor to ew-resize

---

packages/core/src/components/layout/spacer.ts

Use DOMUtils.appendOrSelect() to avoid duplicate spacer component.
No UI impact.

fix: avoid duplicate spacer

---

packages/core/src/components/essentials/tooltip-axis.ts

Instead of hardcoding the formatting for single values, rely on the this.valueFormatter method. Fixes this issue:
https://github.com/carbon-design-system/carbon-charts/issues/778

fix(tooltip): should use valueFormatter for single values

---

packages/core/src/components/graphs/scatter-stacked.ts
packages/core/src/components/graphs/scatter.ts

- abstract getTooltipData function to allow override
- implement getTooltipData function in scatter-stacked with stacked data
The scatter tooltip won't display in stacked charts except first data group because of the different data structure between normal data and stacked data.
Before fix:
After fix:

fix: stacked scatter tooltip not show

---

packages/svelte/src/BaseChart.svelte

Fixes #799
- fix: rewrite component destroy method of `BaseChart.svelte` for usage with the `svelte:component` API
- refactor: initialize `ref`, `chart` variables to `null` instead of `undefined`
TODO:

fix(svelte): fix BaseChart destroy behavior

---

README.md

- docs(readme): add svelte to component status table

docs(readme): add svelte to component status table

---

packages/core/demo/data/index.ts
packages/core/demo/data/zoom-bar.ts
packages/core/src/components/axes/zoom-bar.ts
packages/core/src/components/graphs/scatter.ts
packages/core/src/services/zoom.ts

- allow string dates in zoom bar configurations

fix: allow string dates in zoom bar configurations

---

packages/core/src/components/graphs/scatter-stacked.ts
packages/core/src/model.ts
packages/core/src/services/scales-cartesian.ts

Fixes 2 issues:
- Timescale was missing parsing of JS-dates in 1 place
- Division by zero was being allowed in the stacked area chart

fix(core): fix division by zero & timescale issues

---

packages/core/src/components/essentials/legend.ts
packages/core/src/components/essentials/tooltip-axis.ts
packages/core/src/model.ts

Fix Legend and Tooltip Group colors to be based on the getFillColor option as well
fix #828
- Update Legend fill color function to take into consideration custom fill and stroke colors
- Update Tooltip 'Group' fill color function to take into consideration custom fill and stroke colors

fix(core): fix Legend and Tooltip group color

---

packages/core/src/components/graphs/radar.ts

Currently after the legend hover interaction, radar blobs get a fill-opacity of 100%
This PR will revert the opacity back to the initial state of rendering

fix(core): fix legend hover opacity results in radar graph

---

packages/core/src/components/graphs/scatter-stacked.ts

Provide all data to the customHTML tooltip callback for scatter-stacked, rather than just the group
name, domain and range values.
Before:
After (with additional properties from data series):

fix(core): pass all data to customHTML for scatter-stacked charts

---

packages/core/demo/create-codesandbox.ts

The generated CodeSandbox examples for Svelte chart wrappers use an older CSS stylesheet (`@carbon/charts@v0.30.10`) that is hardcoded in the generation script. This causes some visual discrepancies that can be fixed by always pulling styles from the latest version.
- use latest CDN styles for generated CodeSandbox examples
*Above*: current
*Below*: expected

fix(svelte): use latest CDN styles for generated CodeSandbox examples

---

packages/core/src/components/graphs/gauge.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/charts.ts

`center | left | right` alignment for gauge charts
Closes #870

feat(core): add alignment options for gauge charts

---

packages/core/src/styles/components/_toolbar.scss

- use fill:none to allow transparent toolbar control background. It fixes the problem when user changes the chart background color.
No UI change in demo.

Set toolbar control background to transparent

---

packages/core/src/components/essentials/tooltip.ts

fix(core): tooltips should hide when mouseout is triggered on the chart holder

---

packages/core/src/services/scales-cartesian.ts

wraps user-provided date strings in the `axes.AXIS_POSITION.domain` flag in the options with JS-date objects
Closes #885

fix(core): sanitize user provided axis domains

---

packages/core/src/styles/components/_toolbar.scss

When mouseover to toolbar button background (not the icon), the toolbar button background won't change the color.
It's my bad that I didn't fix it 100% correctly in #858.
- allow toolbar button background color to receive hover state change
- use fill:transparent instead of fill: none
Before fix:
After fix:

Allow toolbar button background to receive hover state change

---

packages/core/src/components/essentials/tooltip.ts
packages/core/src/styles/components/_tooltip.scss

Font sizes in the title tooltips (truncations) are currently inconsistent with our regular tooltips. This PR fixes that issue

fix(core): fix font size issues with title tooltips

---

packages/core/src/model-cartesian-charts.ts

- when set zoom bar data, use defined zoom bar data if exists.
- Without this fix, zoom bar will always use chart data instead of zoom bar data when setData is called.
No change in demos.
It only has impact when zoom bar data is updated in run time.

fix: set definedZoomBarData to zoom bar data

---

packages/core/src/components/axes/zoom-bar.ts
packages/core/src/styles/components/_zoom-bar.scss

- render zoom bar skeleton whenever loading is true
-- needed if charts is changing from loaded to loading
- dispatch Events.ZoomDomain.CHANGE when zoom bar selection is completed
-- useful for user to listen to Events.ZoomDomain.CHANGE instead of Events.ZoomBar.SELECTION_END
- No UI change

Render zoom bar skeleton whenever loading is true

---

packages/core/src/components/essentials/tooltip-axis.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/configuration.ts

- calls `valueFormatter` on all tooltip values
- adds `label` to the valueFormatter.... `(value, label) => ...`

improvement(core): optimize valueFormatter logic in tooltips

---

packages/core/demo/styles.scss
packages/core/src/components/layout/layout.ts
packages/core/stories/all.stories.ts

fixes issues with the legend going outside the chart holder
before
after

fix(core): fix sizing issues with the legend component

---

packages/core/CHANGELOG.md
packages/core/src/components/essentials/tooltip-axis.ts
packages/core/src/components/graphs/area-stacked.ts
packages/core/src/components/graphs/area.ts
packages/core/src/components/graphs/bar-simple.ts
packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/components/graphs/line.ts
packages/core/src/components/graphs/scatter-stacked.ts
packages/core/src/configuration-non-customizable.ts
packages/core/src/services/scales-cartesian.ts
packages/react/CHANGELOG.md
packages/vue/CHANGELOG.md

+ couple of small adjustments to existing code

fix(core): fix minor bug with data values that are undefined

---

packages/core/src/components/graphs/bar-simple.ts

in the example below the bar size ends up being less than 1px, however bc that renders as an invisible bar, we're keeping it at a min of 2px

fix(core): set a min-2px size for simple bars

---

packages/core/src/components/graphs/circle-pack.ts
packages/core/src/model-circle-pack.ts

fix #1031
- fix so that circle pack can have just **one dataset** that is a depth 1

fix(core): fix circlepacks with one dataset

---

packages/svelte/tests/BulletChart.test.svelte
packages/svelte/tests/CirclePackChart.test.svelte
packages/svelte/types/BulletChart.d.ts
packages/svelte/types/CirclePackChart.d.ts
packages/svelte/types/index.d.ts

- add type definitions for BulletChart, CirclePackChart
N/A

feat(svelte): add type definitions for BulletChart, CirclePackChart

---

packages/core/src/components/graphs/scatter.ts

Keep custom fill colors if custom getIsFilled is passed on mouseover for line graph
fix #1032 
- list
- out
- updates
https://user-images.githubusercontent.com/38994122/123815757-be21ae00-d8c4-11eb-84de-503b0a3203fc.mov

 fix(core): keep custom fill colors if custom getIsFilled is passed

---

packages/core/src/components/graphs/circle-pack.ts

Correctly display the tooltip value on hover for circle pack.
fix #1039
- list
- out
- updates

fix(core): display the correct total sum for circle pack

---

packages/core/src/components/graphs/scatter.ts

fix #763
- You will now be able to see first and last scatter elements, but they will not be overlapping the axes due to clipping.

fix(core): display the first and last data elements when addSpaceOnEdges is set to 0

---

packages/core/demo/data/index.ts
packages/core/demo/data/line.ts
packages/core/src/services/scales-cartesian.ts

fix #905 
- Add conditions to set axis based on data values
- Throw error otherwise
- Add log axis example

fix(core): check to see if data values meet log scale type requirements 

---

.github/workflows/release.yml

The new workflow will require the `release` label being added to the PR in order to trigger a release after merging

ci(monorepo): update github release workflow

---

packages/core/demo/create-codesandbox.ts

- Make most style imports local
- Add preconnect `<link>` for plex

docs(svelte): update sandbox styling to support image exports

---

packages/core/stories/tutorials/api.ts
packages/core/stories/tutorials/event-listeners.ts

The [tutorial on event listeners](https://carbon-design-system.github.io/carbon-charts/?path=/story/docs-tutorials--event-listeners) uses "bar-onmouseover" as an example event name. However, the [generated documentation](https://carbon-design-system.github.io/carbon-charts/documentation/enums/_interfaces_events_.bar.html#bar_mouseover) for `Bar` event interfaces lists "bar-mouseover" as the correct enum.
- fix(tutorial): event name should be "bar-mouseover"

docs(tutorials): event name should be "bar-mouseover"

---

packages/core/src/components/graphs/gauge.ts

just moving the arrow-related code inside a `.each()` to make sure that it runs after its parent element has been mounted to DOM

fix(core): gauge delta arrow not showing on first render

---

packages/svelte/README.md
packages/svelte/package.json

Closes #1072 
**Fixes**
- chore(deps): remove `carbon-components` from `peerDependencies`
**Documentation**
- docs: update Svelte charts installation/set-up instructions
- docs: update Svelte chart examples
- docs: add note on TypeScript usage

Rehaul Svelte documentation to focus on vite-powered set-ups

---

packages/core/src/components/essentials/modal.ts
packages/core/src/styles/components/_modal.scss
packages/core/src/styles/components/_toolbar.scss

This is for the `modal` & `overflow-menu` components used from `carbon-components`

fix(core): eliminate style conflicts with carbon-components

---

packages/core/src/services/essentials/files.ts

It's recommended to invoke [`URL.revokeObjectUrl`](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) on an existing data URL when it's no longer needed.
This PR creates and assigns the URL to a variable `href` and revokes it after the download is initiated.
- perf(core): revoke object URL after downloading CSV data

perf(core): revoke object URL after downloading CSV data

---

packages/core/src/styles/styles.scss

we probably don't want any css-reset code coming into the charting styles

fix(core): set $css--default-type to false in the styles

---

packages/angular/src/index.ts

remove `.ts` extension from export

fix(angular): remove .ts from the area chart export

---

packages/core/demo/data/donut.ts
packages/core/demo/data/index.ts
packages/core/demo/data/pie.ts
packages/core/src/components/graphs/donut.ts
packages/core/src/components/graphs/pie.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/charts.ts
packages/core/src/tools.ts

- Add support for mapping value to different keys in pie
- Extended support to donut since it extends pie
- Added value mapping demos for both donut and pie chart
fix #1110

feat(core): Add options to map value to other keys

---

packages/core/src/tools.ts

- Assigned cloned object to a new variable instead of reusing parameter
- Added a condition to delete default controls if toolbar controls are provided by user
- The problem was caused by merging default and provided options (lodash merge), it reassigning array elements of default with provided instead of outright replacing the variable with provided.
- A possible solution too hard coding toolbar in long term is using MergeWith (https://lodash.com/docs/#mergeWith) which allows us to pass in a function. In this function we can probably iterate through the keys and if array, just replace them instead of trying to combine them.
Example of what was happening:
```
const obj1 = { x: ['One', 'Two', 'Three', 'Four'] };
const obj2 = { x: ['Three', 'Four'] };
// Equivalent to Tools.Merge …
```

fix(core): display correct toolbar controls based on provided options

---

packages/core/src/components/graphs/radar.ts

- filter out dots with null or undefined value from being rendered
fix #1133

fix(core): filter out dots with missing value

---

packages/core/src/components/graphs/donut.ts

fix #1146
- Renders donut-title only if value exists
- Automatically renders donut-figure in the center of the circle (User's can still adjust the font-size)

fix(core): display donut-figure in the center when donut-title is empty

---

packages/core/src/components/axes/zoom-bar.ts

- Add condition to display zoom bar in an empty state if there is only 1 data point
fix #996

fix(core): render empty zoom bar holder when there is 1 data point

---

packages/core/src/components/essentials/threshold.ts

- Correctly draw the threshold from all axes regardless the main axes.
fix #1153

fix(core): correctly draw the threshold from multiple axes

---

packages/core/demo/styles.scss
packages/core/src/styles/_chart-feature-flags.scss
packages/core/src/styles/_type.scss
packages/core/src/styles/components/_modal.scss
packages/core/src/styles/components/_toolbar.scss
packages/core/src/styles/styles.scss
packages/core/stories/tutorials/feature-flags.ts
packages/core/stories/tutorials/index.ts

Closes #1168
Closes #1115
- Remove overflow menu and toolbar imports in styles
- Update demo to display overflow menu correctly
- Add feature flags (Similar to carbon) to import fonts

feat(core): remove overflow menu and modal imports in chart styles 

---

packages/core/src/styles/_type.scss

* Change `_type.scss` to use `map-get` to get values from maps. Part of #1168.

fix(styles): use `map-get` in `_type.scss`

---

packages/core/demo/data/alluvial.ts
packages/core/demo/data/index.ts
packages/core/src/components/graphs/alluvial.ts

- Allow users to assign custom colors to node links from source
- Create a demo for it
fix #1175

fix(core): allow users to assign custom colors to the links of source nodes

---

packages/core/src/services/angle-utils.ts

fix #1135
- NaN coordinates are positioned at (0, 0)
- If value equals NaN, then we reassign it value 0 to allow further operations.
https://user-images.githubusercontent.com/38994122/139632321-8b1de3fe-af4f-463c-87ce-fe6963de5423.mov

fix(core): render chart axis labels correctly when data loads async

---

packages/core/demo/create-codesandbox.ts

Currently, the Svelte codesandboxes are broken and will not run.
[Example](https://codesandbox.io/s/tv5sg)
The error is caused by a breaking change introduced in vite version 2.6.8: https://github.com/vitejs/vite/compare/v2.6.7...v2.6.8#diff-00039b783552b3f2a608918986716e01b1a71996da1a8ad5493a102a1e969d7bR279
The solution is to remove the "export default app" line in the `index.html` file.
Example of the solution in practice: https://codesandbox.io/s/objective-cloud-lp4r5?file=/index.html
- fix(svelte): remove default export in `index.html`

fix(svelte): remove default export in `index.html`

---

packages/svelte/tests/AlluvialChart.test.svelte
packages/svelte/tests/HistogramChart.test.svelte
packages/svelte/tests/TreeChart.test.svelte
packages/svelte/types/AlluvialChart.d.ts
packages/svelte/types/BaseChart.d.ts
packages/svelte/types/HistogramChart.d.ts
packages/svelte/types/TreeChart.d.ts
packages/svelte/types/index.d.ts

This PR is best reviewed by commit.
**Testing locally**
1. Run `yarn; yarn build` at the root of the monorepo
2. In `packages/svelte`, run `yarn test`
3. Validate that no errors or warnings are emitted by `svelte-check`
- feat(svelte): add TypeScript definitions for Alluvial, Histogram, and Tree charts

feat(svelte): add TypeScript definitions for Alluvial, Histogram, and Tree charts

---

packages/core/demo/data/hightlight.ts
packages/core/src/axis-chart.ts
packages/core/src/styles/components/_highlights.scss

- Sets pointer events of highlight element to none so users can use the ruler & hover over the chart elements.

fix(core): set pointer events of highlight elements to none

---

packages/core/src/components/axes/zoom-bar.ts

-  if existing initial zoom domain is undefined, we should still reset initial zoom domain (and zoom domain) if new initial zoom domain is null.
No UI/storybook change.

fix: set zoom domain if old initial zoom domain is undefined

---

packages/react/src/diagrams/CardNode/CardNode.tsx
packages/react/src/diagrams/CardNode/CardNodeColumn.tsx
packages/react/src/diagrams/CardNode/CardNodeLabel.tsx
packages/react/src/diagrams/CardNode/CardNodeSubtitle.tsx
packages/react/src/diagrams/CardNode/CardNodeTitle.tsx
packages/react/src/diagrams/Edge/Edge.tsx
packages/react/src/diagrams/Marker/Marker.tsx
packages/react/src/diagrams/ShapeNode/ShapeNode.tsx

The CardNode component has a `color` prop which can be used to specify the
colour of the border applied on the outer node. However, this requires the
code to be aware of the active theme, handle dark mode, etc. to select an
appropriate colour in some cases.
For component libraries this can be problematic as now both the components
and their consumers need to be aware of theme rather than relying on this
being handled entirely in (S)CSS.
Add support for applying a custom class to the CardNode component which will
be applied to the outer node and can be used to apply styles to the card and
its children, including specifying the border colour for the card.
resolves #1221
Add similar `className` prop to all diagram components for consistency.

feat(react diagrams): add support for applying a custom class to the outer node

---

packages/core/src/components/graphs/scatter-stacked.ts
packages/core/src/model/model.ts

- Render the scatter points only if the status of the data group is true.
fix #1188

fix(core): display the correct group when hovering over scatter point

---

packages/core/src/components/essentials/tooltip-axis.ts

- All charts with dual axes & combo charts were displaying incorrect range label on secondary axes data set
- Check to see what type of chart it is (dual axes or not) and determine the correct range label.
fix #1085

fix(core): display respective combochart tooltips range label

---

packages/core/src/components/axes/toolbar.ts

fix #1229
- When data is loading, we set the overflow menu to null since the DOM Element no longer exists
- This will force a re render of the overflow menu and it's list
https://user-images.githubusercontent.com/38994122/145088761-b53e65c4-3121-4ffa-9a16-8543b9015eee.mov

fix(core): fix overflow menu caused by data loading option change

---

packages/core/src/services/zoom.ts

- Set zoom bar domain to the initial domain defined in axes
- User can use initialDomain in zoom bar options to zoom in into min/max value. T
- User must calculate extent
fix #1228

fix(core): use domain in zoom bar if defined in axes

---

packages/core/src/components/essentials/color-scale-legend.ts
packages/core/src/services/canvas-zoom.ts

- Remove circular imports from color scale legend and canvas zoom files
- Remove unused imports

fix(core): remove circular dependencies inheritance from heatmap legend & canvas zoom files

---

packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/components/graphs/bar.ts
packages/core/src/model/model.ts

This fixes the #1232 issue:
The solution is to override the default method for getting width of the bar width for the  `StackedBar` :
https://github.com/carbon-design-system/carbon-charts/blob/b11873b24c3ca19ef07381b1647be70be33b4baf/packages/core/src/components/graphs/bar.ts#L7-L27
with the analogous method which uses `this.model.getStackKeys().length;` as the count of data points on domain we divide in line 22 of default method: https://github.com/carbon-design-system/carbon-charts/blob/b11873b24c3ca19ef07381b1647be70be33b4baf/packages/core/src/components/graphs/bar.ts#L22
instead of using `this.model.getDisplayData().length;` which just gets length of whole visible data, thus for charts with many series, the greater the number of series is, the thinner the bars are.
before fix:
after …

fix(stacked-bar): set bar width based on number of domain values

---

packages/core/src/components/graphs/area.ts
packages/core/src/services/scales-cartesian.ts

- Added a function that updates the upperBound range value if includeZero is enabled for a specific axes
- Does not affect percentage or stacked
- Removed unused import (d3-array sum) in Cartesian service
fix #1248

fix(core): prevent area chart from bleeding out of cartesian plane when includeZero is enabled

---

packages/core/src/components/graphs/radar.ts

- Align the chart after the transitions are complete, previously alignment was triggered async which caused it to be misaligned after fullscreen exit
fix #1247

fix(core): keep radar chart alignment after fullscreen exit

---

packages/core/src/components/graphs/circle-pack.ts

- Prevent canvas zoom on click completely if property is set to false
fix #1251
N/A no longer allows zooming when depth is 2 and canvas zoom property is set to false.

fix(core): prevent canvas zooming if depth equals 2 and canvas zoom property is set to false

---

packages/core/src/components/graphs/bar-stacked.ts
packages/core/src/services/scales-cartesian.ts
packages/core/src/styles/_chart-holder.scss
packages/core/src/styles/components/_skeleton.scss

- Checks to see if thresholds is an array and an additional check to see if it is empty
- Prevents chart from crashing
- Formats (other) files
fix #1264 
N/A - any cartesian chart with thresholds set to empty array:
```json
options: {
axes: {
left: { thresholds: [] }
}
}
```

fix(core): prevent chart from breaking if thresholds array is empty 

---

packages/core/src/services/scales-cartesian.ts

- Axis position is retrieved by passing in the datum to ensure the coordinates match axis
fix #1253

fix(core): position bounds correctly in secondary axis of combo chart

---

packages/core/src/components/graphs/radar.ts

fix(radar): only show active datapoints in tooltips

---

packages/core/demo/data/heatmap.ts
packages/core/demo/data/index.ts
packages/core/src/components/essentials/color-scale-legend.ts
packages/core/src/model/heatmap.ts

- Heatmap domain now supports small values (No user change required)
fix #1321

fix(core): enable heatmap value domain to support small values

---

packages/core/demo/data/alluvial.ts
packages/core/demo/data/index.ts
packages/core/src/components/graphs/alluvial.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/charts.ts

- Add alluvial alignment options (Left, Right, Justify)
- Default is 'Justify' (Center)
- Added demo
**Before**:
*Using default alignment - center (justify)
**After**:
*Using alignment left

feat(core): add alignment option to alluvial 

---

packages/svelte/README.md

This updates the documentation for the SvelteKit example.
The `kit.target` option was removed in [v1.0.0-next.257](https://github.com/sveltejs/kit/blob/571831a923fead2a4a8c7d82bc1066a7f61d0221/packages/kit/CHANGELOG.md#100-next257). 
- docs(svelte): remove `kit.target` from SvelteKit set-up
I tested this locally with both SvelteKit and SvelteKit + TypeScript set-ups in this repo: https://github.com/metonym/carbon-charts-svelte-examples

docs(svelte): remove `kit.target` from SvelteKit set-up

---

packages/svelte/package.json

This removes the `email` field as I am no longer employed by IBM.
- chore(svelte): remove old email from package metadata

chore(svelte): remove old email from package metadata

---

packages/core/src/model/heatmap.ts

fix #1385
- Added conditional to check if domain does not range from zero to zero, if the case we set the domain to [0, 1]
You can also use the data provided in issue #1385 to check in storybook

fix(core): add condition to check if domain is not undefined

---

packages/svelte/README.md
packages/svelte/src/BaseChart.svelte
packages/svelte/types/BaseChart.d.ts

This PR adds a `theme` prop to the Svelte base chart to make theming easier. It also updates the documentation on using the v1 Svelte charts based on the process of updating [metonym/carbon-charts-svelte-examples](https://github.com/metonym/carbon-charts-svelte-examples/commit/8ec690a83a0778c6a60fede22d8a01a9ad4459b5).
- feat(svelte): add `theme` prop to chart wrappers
- docs(svelte): update docs on v1 usage
- docs(svelte): update docs on theming
I've tested the updated type definitions locally.

feat(svelte): add `theme` prop

---

packages/core/src/components/axes/toolbar.ts
packages/core/src/services/essentials/dom-utils.ts

closes #1390
- Each `chart` now has an id element
- Initializing chart id in init function (it is called before constructor is called 🤔)
- Decided to add `id` to the chart to clarify what the toolbar aria-label is referring too
- Added aria-label attribute to toolbar container
- Aria label has the following label: `chart-${id} toolbar`
- Using aria-label instead of aria-labelledby since we do not have text within container (only icon)
- 4.1.2 Name, Role, Value is no longer reported by the checker

fix(core): add aria-label attribute to toolbar container

---

packages/core/demo/data/bar.ts
packages/core/demo/data/index.ts
packages/core/demo/data/zoom-bar.ts
packages/core/src/components/graphs/bar-grouped.ts

Extends existing grouped bar support to time series scales. This should address
https://github.com/carbon-design-system/carbon-charts/issues/1396 and
https://github.com/carbon-design-system/carbon-charts/issues/1373
fix #1396, #1373
- Grouped bar can now support ```scaleType: 'time'```
[storybook-sm.mov.zip](https://github.com/carbon-design-system/carbon-charts/files/8952483/storybook-sm.mov.zip)

feat(core): bar group time series

---

packages/core/src/components/axes/axis.ts

Remove mock text element from DOM.
I noticed odd text elements with value A accumulating in the DOM for time-series charts, e.g.
Seems there was a mock text element being added to obtain avg letter width but wasn't being removed.

fix(core): remove mock text from axes

---

packages/core/demo/styles.scss
packages/core/demo/utils.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/charts.ts
packages/core/src/interfaces/enums.ts
packages/core/src/services/essentials/dom-utils.ts
packages/core/stories/tutorials/themes.ts
packages/svelte/src/BaseChart.svelte

fix #1411
- Updates docs to use `theme` option when `theme` radio value is selected.
- Marks svelte _additional_ `theme` as deprecated since V1
- In next major version, should be removed
- Creates a new option called `theme` set to `white` by default. Accepts  `white`, `g10`, `g90`, `g100` as values, where `white` is default value.

feat(core): allow theme to be set via options prop

---

packages/core/demo/data/bar.ts
packages/core/demo/data/index.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/model/model.ts
packages/core/src/services/time-series.ts

If there are multiple data set in the same second (different millisecond) in time-serious stacked bar chart, only one data is displayed, and the other data will be ignored due to stacked key conflicts.
- Include millisecond as part of time serious stacked keys to avoid conflicts
- Add a new short time interval stacked bar (all data are in the same second)
-- http://localhost:9006/?path=/story/simple-charts-bar-stacked--vertical-stacked-bar-short-interval-time-series

feat(core): Show milliseconds in axis labels if necessary

---

packages/svelte/README.md

As of June 2022, Sapper is officially [deprecated](https://github.com/sveltejs/sapper/commit/ef01df6f4e891680f2257a646d70c3cdf03fe45b).
- docs(svelte): remove Sapper set-up instructions

docs(svelte): remove Sapper set-up instructions

---

packages/svelte/README.md

As of April 2022, Snowpack is [no longer maintained](https://github.com/FredKSchott/snowpack/blob/7f9b5455683a9d7632dbd7f4ed6db9ec2bb7c760/README.md?plain=1#L1-L4). Vite is the recommended alternative.
- docs(svelte): remove Snowpack set-up instructions

docs(svelte): remove Snowpack set-up instructions

---

packages/svelte/README.md

I've noticed that the set-up instructions for SvelteKit are out of date as it will no longer build properly when using the latest SvelteKit version. SvelteKit recently updated to use Vite version 3.
The gist of the change is that both `@carbon/charts` and `carbon-components` should *not* be externalized for SSR if using SvelteKit. This isn't needed for the Vite standalone set-up. `@carbon/charts` no longer needs to be optimized for SvelteKit, but is still required if using Vite standalone.
Grammatical changes include capitalizing "Webpack" and "Vite."
- docs(svelte): update SvelteKit/Vite set-up instructions
I've tested the updated set-ups in [metonym/carbon-charts-svelte-examples](https://github.com/metonym/carbon-charts-svelte-examples). I've ensured that the config works in both …

docs(svelte): update SvelteKit/Vite set-up instructions

---

packages/core/src/components/axes/toolbar.ts

fix #1424
- Checks to see if shouldBeDisabled exists
- If it exists, runs the function
- If it doesn't exist, we automatically assume the toolbar button click function should execute

fix(core): prevent toolbar buttons from being clicked if shouldBeDisabled returns true

---

packages/core/carbon.yml

Related: https://github.com/carbon-design-system/carbon-platform/issues/967
The Carbon Charts libraries have a design kits page, so you can easily find which design kits are compatible with the libraries.
https://next.carbondesignsystem.com/libraries/carbon-charts/latest/design-kits
There's one data viz Sketch design kit. This PR adds it to the core package, and because the schema `designKits` array is inherited, all 5 Carbon Charts libraries will show the Sketch kit in their design kits page.

docs: index compatible design kits

---

packages/core/src/components/graphs/heatmap.ts

fix #1439
- Highlight cell in the chart that has the cell.
- Select cell from parent

fix(core): highlight correct cell when multiple heatmaps exist

---

packages/core/src/components/graphs/heatmap.ts

fix #1423
- Display correct minimum in heatmap axis tooltip
- If entire column or row consists of missing data, display `-` (dash)
- This is possible by passing in custom domain

fix(core): display correct minimum in heatmap axis tooltip when there is missing data

---

packages/core/src/interfaces/axis-scales.ts
packages/core/src/interfaces/charts.ts

Fixes #1413
The `AxisOptions` interface is missing `main` and `correspondingDatasets` properties to support dual-axes charts.
- add missing properties to AxisOptions interface

fix(core): add missing properties to AxisOptions interface

---

packages/core/src/components/graphs/wordcloud.ts

this PR adds a check where if the `value` field provided is not a number, it'll stop the rendering and throw an error

fix(core): wordcloud should not render if `value` is not a number

---

packages/core/src/components/axes/hover-axis.ts

fix #1453
- Accessibility fix, allows users to escape (hide) the tooltip for HEATMAP axis
- When tooltip is hidden, the axis tick will remain highlighted
- Going to the next or previous tick will show the tooltip again

fix(core): allow users to 'escape' axis tooltip in heatmap

---

thumbnails/bar-stacked.svg
thumbnails/gauge.svg
thumbnails/heat-map.svg
thumbnails/tree-map.svg

Closes https://github.com/carbon-design-system/carbon-platform/issues/1432
Reported https://github.com/carbon-design-system/carbon-platform/issues/1315
- Makes sure white divider lines show up on hover for bar stacked, gauge, heat map, and tree map thumbnails
Hovering:

fix: thumbnail hover bugs

---

packages/core/src/components/essentials/legend.ts

fix #1470
- Check legend truncation type to see if tooltip should be shown.
- If legend truncation type is set to `none` then tooltip is not shown since it is redundant
- Removed unused variable (line 405)
- Emit tooltip events only if tooltip was shown on hover (Copied same logic to mousemove & mouseleave)

fix(core): keep tooltip hidden if legend truncation is set to none

---

.github/CONTRIBUTING.md
.github/workflows/dco.yml

- Adds carbon-dco workflow
- Adds legal notice to `contribution.md`
`GITHUB_TOKEN` is auto-generated for each action, but we will need the `carbon-bot` PAT (`CARBON_BOT_DCO`) with repo scope permissions.

ci(actions): add carbon-dco workflow to repo

---

packages/svelte/README.md

Best reviewed by commit.
This updates the docs to address a couple of major changes to common set-ups:
- Rollup version 3 (`onwarn` usage is out-of-date)
- SvelteKit version 1
These changes were tested with various set-ups in https://github.com/metonym/carbon-charts-svelte-examples
- docs(svelte): update `onwarn` usage to work with Rollup version 3
- docs(svelte): update code-splitting guidance for Rollup
- docs(svelte): update SvelteKit set-up to work with version 1

docs(svelte): update guidance for Rollup, SvelteKit set-ups

---

packages/react/src/utils.ts

Closes #1500
Seems like react wrappers were still looking for the v10 prefix!

fix(react): outdated Carbon prefix being used

---

packages/core/src/model/model.ts

Two lines changed in core/src/model/model.ts to replace use of deprecated histogram function in d3-array with bin. Functionality remains the same but modification prevents break in future release.

fix(model): d3-array histogram deprecated / replaced by bin

---

.vscode/settings.json
package.json
packages/core/package.json
packages/react/package.json
packages/svelte/package.json
packages/vue/package.json
prettier.config.cjs
yarn.lock

- Revert to prettier 2.8.8 for lerna publish (no idea why it cares about the prettier version but it does)
- Revert config file to CJS for now
- Update .vscode/settings to look for CJS file
- Update root-level package.json to point to prettier.config.cjs
- Bug fix for Svelte 4
- Bug fix for Vite

fix(lerna): revert prettier to 2.8.8 for now

---

packages/core/src/model/meter.ts

fix #1604
Add an initial value to the `reduce` function so that proportional meter chart doesn't error out when receving an empty array.
https://github.com/carbon-design-system/carbon-charts/assets/38139823/17f32441-8539-4028-9166-fd201009c6ad
https://github.com/carbon-design-system/carbon-charts/assets/38139823/30ca1048-ce95-4ecd-9b53-7970dff4f4ab

fix(meter.ts): meter chart no longer have reduce error on empty data

---

packages/core/src/charts/area.ts
packages/core/src/charts/combo.ts
packages/core/src/charts/meter.ts
packages/core/src/components/axes/axis.ts
packages/core/src/components/axes/ruler-binned.ts
packages/core/src/components/axes/ruler.ts
packages/core/src/components/axes/zoom-bar.ts
packages/core/src/components/component.ts
packages/core/src/components/essentials/color-scale-legend.ts
packages/core/src/components/graphs/alluvial.ts
packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/components/graphs/gauge.ts
packages/core/src/components/graphs/line.ts
packages/core/src/components/graphs/radar.ts
packages/core/src/components/graphs/wordcloud.ts
packages/core/src/configuration.ts
packages/core/src/model/cartesian-charts.ts
packages/core/src/model/choropleth.ts
packages/core/src/model/circle-pack.ts
packages/core/src/model/heatmap.ts
packages/core/src/model/model.ts
packages/core/src/services/color-scale-utils.ts
packages/core/src/services/essentials/dom-utils.ts
packages/core/src/services/scales-cartesian.ts
packages/core/src/tools.ts

Second part of refactor to make lodash-imports friendly to tree shaking.
I don't see any reason for tools.ts to re-export the lodash methods.  It makes tree shaking more difficult and it also gives other code two ways to import the lodash methods, which could lead to inconsistency (ex: ruler-binned.ts).
This mainly changes where methods are imported from, but it also reverts clone() to its original name cloneDeep(), and reverts removeArrayDuplicates() to its original name uniq().
Fixes #1507.

Stop re-exporting lodash from tools.

---

package.json
packages/svelte/README.md
yarn.lock

- Downgrade to prettier 2.8.8 due to prettier-plugin-svelte (lerna issue is resolved).

fix(prettier): downgrade for now

---

package.json
yarn.lock

- lerna version has some checks for prettier for some unknown reason. One of those checks is to look for `prettier-plugin-svelte` in the top-level node_modules. But it normally resides in packages/svelte/node_modules. This update adds it as a devDependency to the top-level package.json to force it to be hoisted.
- [An issue](https://github.com/lerna/lerna/issues/3788) has been opened on Lerna's GitHub to get the problem corrected.

fix(lerna version): hoist prettier-plugin-svelte due to lerna bug

---

.prettierignore
.vscode/settings.json

- `lerna version` for some unknown reason messes with prettier. Because prettier's ignore is set in .vscode/settings.json (and points to eslint's ignore file), it tries to parse yarn.lock. This PR creates a prettier ignore file that is identical to the eslint ignore file so lerna knows not to parse yarn.lock.

fix(lerna): lerna version doesn't know we are sharing eslintignore file

---

packages/vue/package.json

- When using `@carbon/charts-vue` in an environment with vite, an error would be displayed because the package did not an export like this:
```json
".": {
"style": "./dist/styles.css",
"types": "./dist/index.d.ts",
"default": "./dist/index.mjs"
}
```
Closes https://github.com/carbon-design-system/carbon-charts/discussions/1641

Fix vite error with Vue3 caused by package.json exports lacking a "." property (issue 1641)

---

packages/core/src/tools.ts

- packages/core/src/tools.ts:debounceWithD3MousePosition():12 returned arrow function where there is no lexical this. Changed to return standard function.
- closes https://github.com/carbon-design-system/carbon-charts/issues/1633

fix(1633): use of arrow function lost lexical this

---

packages/angular/README.md
packages/angular/package.json

- Fixes https://github.com/carbon-design-system/carbon-charts/issues/1650
- For version 1.8.0 of `@carbon/charts-angular`, the dependency on `@carbon/charts` was `^1.8.0`. Many changes were introduced in `1.9.0` and later that were not designed for `@carbon/charts-angular` 1.8.0. This PR updates the package.json  so the core dependency is now `~1.8.0` to keep it from installing an incompatible version.
- Also, the README.md has been updated to let users know about where to get support for Angular 16 and newer using the dist tag `next`.
Only `@carbon/charts-angular@1.8.1` will be published.

fix(charts-angular): issue 1650 - @carbon/charts-angular 1.8.1 release

---

packages/core/src/components/graphs/pie.ts
packages/core/src/tools.ts

- Added percentageValue property to formatter
- User can now edit labels

fix(pie-donut): formatter not recieving entire value

---

packages/core/package.json
packages/core/scss/_chart-holder.scss
packages/core/scss/index.scss
yarn.lock

- Moves loading of SCSS tokens to top of _chart-holder.scss so all CSS custom properties like --cds-grid-bg are set correctly.
- Simplies index.scss as the loading of the tokens needed to happen earlier anyway
- bump vitest
- Closes https://github.com/carbon-design-system/carbon-charts/issues/1663

fix(scss): load tokens at beginning of _chart-holder.scss

---

packages/core/src/components/essentials/tooltip.ts

-[#1448](https://github.com/carbon-design-system/carbon-charts/issues/1448)
-Numeric value is formatted when truncation is set to none.

fix(tooltip-#1448):Issue with numeric value in tooltip when truncation type set to none

---

packages/core/src/components/essentials/legend.ts

-[#1529](https://github.com/carbon-design-system/carbon-charts/issues/1529)
-Tooltip will only be displayed for truncated legends.
-Length of legend will be taken into consideration while truncation of legend

fix(legend-#1529):Legend truncation value has no effect on tooltip display and issue with length of legend and its truncation

---

packages/core/src/components/essentials/modal.ts

- [#1570](https://github.com/carbon-design-system/carbon-charts/issues/1570)
- ARIA properties removed when modal is closed

fix(modal-#1570):ARIA properties added to modal whilst being unopened

---

packages/core/src/components/axes/toolbar.ts

- [#1560](https://github.com/carbon-design-system/carbon-charts/issues/1560)
-Chart toolbar buttons were enclosed in div with a role of button
-Issue fixed by removing said role

Accessibility toolbar btn #1560

---

packages/svelte/README.md

This PR is a docs suggestion to simplify the "Event listeners" example.
- Use the `return function` in `onMount` instead of `onDestroy
- Use optional chaining operator on `charts`
- Add event listener in `onMount` instead of a reactive statement
I've tested this in my repo: https://github.com/metonym/carbon-charts-svelte-examples
- docs(svelte): simplify "Event listeners" example

docs(svelte): simplify "Event listeners" example

---

packages/svelte/README.md

This PR proposes bolstering the TypeScript section of the README to include simple examples for reference. These are based on my own experience.
For example, it seeks to answer:
- How can I strongly type options passed to charts?
- How can I type a chart when dynamically importing it?
- How can I get the prop types for a component? A specific property on the type?
- docs(svelte): add TypeScript reference

docs(svelte): add TypeScript reference

---

packages/svelte/src/lib/BaseChart.svelte

Currently, the TypeScript definitions for Svelte components are auto-generated by `@sveltejs/package`. However, the exact types for the dispatched events use `any`.
For example, they currently look like:
```ts
declare const __propDef: {
props: {
[x: string]: any;
options: BarChartOptions;
data: ChartTabularData;
chart?: SimpleBarChartCore | null;
ref?: HTMLDivElement | null;
};
events: {
load: CustomEvent<any>;
update: CustomEvent<any>;
destroy: CustomEvent<any>;
} & {
[evt: string]: CustomEvent<any>;
};
slots: {};
};
```
The solution is to define the types for dispatched events, and pass it as a type variable to the generic `createEventDispatcher`.
To test this, I ran `yarn build:package` and inspected the generated types:
```ts
declare const __propDef: {
props: {
[x: string]: any; …
```

fix(svelte): strongly type dispatched events

---

packages/core/src/model/pie.ts

- https://github.com/carbon-design-system/carbon-charts/issues/1693
- removal of hardcoded 'value' property in getTabularDataArray
- valueMapsTo will be checked for property name

fix(pieModel) : Unable to view model and export CSV while using valueMapsTo

---

packages/angular/package.json
packages/core/package.json
packages/core/vite.config.ts
packages/react/vite.config.ts
packages/vue/package.json
packages/vue/vite.config.ts
yarn.lock

- Set package.json for all modules to type = module
- Remove unnecessary build.optimizeDeps.include elements since vite now handles them correctly
- For packages that only export a single index.mjs file, remove function and hard-code name

refactor(vite config): Cleanup vite configs and set all packages to type module

---

.github/workflows/dco.yml
.github/workflows/release.yml
package.json
packages/angular/package.json
packages/core/package.json
packages/react/.storybook/main.ts
packages/react/package.json
packages/svelte/package.json
packages/vue/package.json
yarn.lock

- Bump Github actions, SvelteKit, date-fns, @angular/cli, @angular/devkit, vue-tsc
- Remove yarn resolutions in top-level package.json
- Remove invalid exports from package.json (react and vue)

Bump date-fns, SvelteKit and minor devDependencies, cleanup exports

---

packages/react/README.md
packages/react/package.json
packages/react/telemetry.yml
yarn.lock

Adds config file and dependency necessary to start tracking telemetry data via [IBM Telemetry](https://github.com/ibm-telemetry/telemetry-js)
- Updates readme telemetry disclosure
- Removes `@carbon/telemetry` dependency
- Adds @ibm/telemetry-js dependency
- Updates postinstall script to use IBM telemetry command
- Adds [telemetry.yml](packages/react/telemetry.yml) config file
- Include `telemetry.yml` in package.json files config 
Please look through [telemetry.yml](packages/react/telemetry.yml) config file and ensure desired props/values have been captured. For more info see [Telemetry Config Schema](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#jsx-scope)
N/A

chore: onboard @carbon/charts-react to ibm telemetry

---

packages/angular/README.md
packages/angular/ng-package.json
packages/angular/package.json
packages/angular/telemetry.yml
packages/core/README.md
packages/core/package.json
packages/core/telemetry.yml
packages/core/vite.config.ts
packages/react/.storybook/main.ts
packages/svelte/README.md
packages/svelte/package.json
packages/svelte/telemetry.yml
packages/vue/README.md
packages/vue/package.json
packages/vue/telemetry.yml
yarn.lock

Adds config files and dependencies necessary to start tracking telemetry data via [IBM Telemetry](https://github.com/ibm-telemetry/telemetry-js) on `@carbon/charts`, `@carbon/charts-svelte`, `@carbon/charts-vue` & `@carbon/charts-angular`
- Adds readme telemetry disclosure to `@carbon/charts`, `@carbon/charts-svelte`, `@carbon/charts-vue` & `@carbon/charts-angular`
- Removes `@carbon/telemetry` dependency from `@carbon/charts`, `@carbon/charts-svelte`, `@carbon/charts-vue` & `@carbon/charts-angular`
- Adds @ibm/telemetry-js dependency to `@carbon/charts`, `@carbon/charts-svelte`, `@carbon/charts-vue` & `@carbon/charts-angular`
- Updates postinstall script to use IBM telemetry command `@carbon/charts`, `@carbon/charts-svelte`, `@carbon/charts-vue` & `@carbon/charts-angular`
- Adds …

chore: onboard other charts flavors to IBM Telemetry

---

.github/ISSUE_TEMPLATE/ACCESSIBILITY.yaml
.github/ISSUE_TEMPLATE/BUG_REPORT.yaml
.github/ISSUE_TEMPLATE/ENHANCEMENT.yaml
.github/ISSUE_TEMPLATE/QUESTION.yaml

- This update removes the PII questions across issue templates, and instead asks for the application/team information if coming from IBM.

fix(github): removing PII question from issue forms

---

packages/core/src/components/axes/toolbar.ts

removed the chartID from aria-label attribute.
related issue: https://github.com/carbon-design-system/carbon-charts/issues/1728

including a random id in the aria-label does not help screenreader users

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yaml
package.json
packages/vue/package.json
yarn.lock

- change export for @carbon/charts-vue from "default" to "import" in case StackBlitz is trying to load via require
- bump prettier
- minor tweaks to bug tracking template
- might close https://github.com/carbon-design-system/carbon-charts/issues/1740

fix(stackblitz/vue): remove export ambiguity

---

package.json
packages/core/src/demo/utils/package-versions.ts
packages/core/src/demo/utils/stackblitz/vue.ts
yarn.lock

- StackBlitz 'vue' template does not load library correctly as ESM. Moved template to 'node' so vite does the loading.
- Remove hard-coded package versions for demos. Either get the version the package uses or if the package doesn't use it and StackBlitz's template needs it, use the latest to ensure StackBlitz compatibility
- Refactor Vue examples to use Vue 3.4 v-bind sugar.
- Bump @nrwl/devkit

fix(stackblitz/vue): workaround for stackblitz bug

---

packages/core/scss/components/toolbar/_modal.scss

Closes #1730
- Fix css selector or primary button in export to csv modal
After fixing the css selector, we can see the styles in _modal.scss are applied.

fix(modal): styles of export to csv button

---

packages/core/src/components/axes/toolbar.ts
packages/core/src/interfaces/enums.ts
packages/core/src/services/essentials/dom-utils.ts

Closes: #1284
- Add carbon minimized icon when in full screen mode
Now we can see carbon minimized icon when chart is displayed in fulls creen mode.

fix(toolbar): add minimized icon for fullscreen

---

packages/core/scss/components/toolbar/_modal.scss

Closes #1730
- Fix `padding-inline-start` and `padding-inline-end` of export to csv button.
Add the missing variable for padding of button

fix(modal): padding of export to csv button

---

packages/core/scss/_chart-holder.scss

Closes #1753 
- Remove css selector `.#{globals.$prefix}--chart-holder:-webkit-full-screen` and only leave `.#{globals.$prefix}--chart-holder.fullscreen` then it would give expected behaviors in both Chrome/Firefox/Safari/Edge.
Can try on preview with firefox or using developer tools do live editing to see this behavior.

fix(charts): missing paddings on firefox fullscreen

---

packages/core/src/configuration.ts

Fixes #1755
`window.navigator` is a browser API. This PR adds a check so that Carbon Charts can be used with SSR.
- fix(config): add SSR guard for `window.navigator`

fix(config): add SSR guard for `window.navigator`

---

packages/core/src/charts/choropleth.ts
packages/core/src/charts/heatmap.ts

- https://github.com/carbon-design-system/carbon-charts/issues/1759
- hiding legend when data array is empty for heatmap and choropleth charts

fix(heatmap-choropleth):legend hidden when data array is empty

---

packages/core/src/components/essentials/modal.ts

- [#1670](https://github.com/carbon-design-system/carbon-charts/issues/1670)
- Repeated classes removed from modal.

fix(modal):removal of repeated classes from modal

---

packages/core/src/components/graphs/gauge.ts
packages/core/src/configuration.ts

- Removal of default gauge numberFormatter
- Created gauge numberFormatter conditional thus when not passed, defaults to localeNumberFormatter.
When gauge numberFormatter is passed:
When gauge numberFormatter is not passed:
Default:

fix(gauge):conditional gauge numberFormatter

---

packages/core/src/components/graphs/pie.ts
packages/core/src/configuration-non-customizable.ts

- Fix #1685
- Fix #1764
- use debounce for mouse events to prevent distortion on leaving fullscreen
- add a variable `isRendering` to prevent mouse events fired on rendering animation
Thanks to @ilyas-sov, using the code here for verifying: https://stackblitz.com/edit/react-imtvrq?file=src%2Findex.js,src%2Fdata.js,package.json
1. Deleted by mouse
2. Deleted by keyboard + mouse over (easier for verifying)
3. Verifying the donut distortion of issue 1685:
1. Open https://deploy-preview-1771--carbon-charts-core.netlify.app/?path=/story/simple-charts-donut--donut
2. Enter fullscreen mode
3. Mouse over to one of the slices
4. Press "ESC"

fix(pie): distortion issues of hovered slices

---

packages/core/scss/components/_tooltip.scss
packages/core/src/components/axes/toolbar.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/configuration-non-customizable.ts
packages/core/src/configuration.ts
packages/core/src/interfaces/components.ts
packages/core/src/interfaces/events.ts
packages/core/src/services/essentials/dom-utils.ts

Closes #1549 
- Add tooltip (with top placement) for toolbars
- Expose more translation strings
1. Mouse hovering on toolbar and it should display the tooltips
2. Using tab can trigger toolbar focus and display the tooltips
3. Hover the label title -> press tab to get toolbar focus -> move mouse over the label title should still see consistent tooltip content. 
4. Can apply following options to check translated strings
https://deploy-preview-1766--carbon-charts-angular.netlify.app/?path=/story/utility-truncations--truncated-labels-simple-bar
5. Repeat 1-4 in full screen mode
```
{
"title": "Truncated labels (simple bar)",
"locale": {
"translations": {
"toolbar": {
"makeFullScreen": "進入全螢幕",
"exitFullScreen": "離開全螢幕",
"showAsTable": "顯示為表格",
"moreOptions": "更多選項",
"exportAsCSV": "轉存為CSV", …
```

feat(toolbar): add tooltips

---

packages/core/src/components/essentials/title-meter.ts
packages/core/src/model/alluvial.ts
packages/core/src/model/choropleth.ts
packages/core/src/model/heatmap.ts
packages/core/src/model/meter.ts
packages/core/src/model/treemap.ts

- https://github.com/carbon-design-system/carbon-charts/issues/1767
- Added '-' for chart null values

fix(tabular-rep): better handling of null values

---

packages/core/src/components/graphs/bar-grouped.ts
packages/core/src/services/scales-cartesian.ts

- Closes #1776
- Calculate a lower bound and set to grouped-bar chart when includeZero is set to false in the data axis.
**Test 1: v1.15.2 vertical grouped bar with includeZero set to false**
- Before: https://charts.carbondesignsystem.com/?path=/story/simple-charts-bar-grouped--vertical-grouped-bar-time-series&args=options.axes.left.includeZero:!false
- After: https://deploy-preview-1780--carbon-charts-angular.netlify.app/?path=/story/simple-charts-bar-grouped--vertical-grouped-bar-time-series&args=options.axes.left.includeZero:!false
**Test 2: v1.15.2 horizonal grouped bar with includeZero set to false**
- Before: https://charts.carbondesignsystem.com/?path=/story/simple-charts-bar-grouped--horizontal-grouped-bar-time-series&args=options.axes.bottom.includeZero:!false
- After: …

fix(bar): bleed-out for includeZero set to false

---

packages/core/src/components/graphs/pie.ts

- Closes #1783.
- fix uncaught errors on pie/donut chart load. Quite tricky, I can only re-produce it on production mode.
**Before (uncaught promise):**
https://deploy-preview-1771--carbon-charts-core.netlify.app/?path=/story/simple-charts-donut--donut
**After:**
https://deploy-preview-1784--carbon-charts-react.netlify.app/?path=/story/simple-charts-donut--donut-centered

fix(pie): uncaught exception on pie and donut chart load

---

packages/react/src/diagrams/CardNode.tsx
packages/react/src/diagrams/ShapeNode.tsx

- class provided as props is not getting appended to carbon charts classes
- addition of className prop to ShapeNode and CardNode

fix(cardNode-shapeNode):addition of className to props

---

packages/core/src/components/graphs/meter.ts

- sets a minimum width of 2px for meter rectangle (this was already in place in case of a value of 0)

fix(meter): meter width shouldn't be smaller than 2px

---

packages/react/package.json

fix the restricted exports provided by package.json to allow scss to import
- adds in a more generic ./styles import so A. you don't have to provide an explicit import of a .css file and B. scss can now handle loading that file using @use instead of @import

fix: Update package.json style export

---

packages/core/package.json
packages/core/vite.umd.config.ts
packages/react/package.json
packages/react/vite.config.ts

- Vite.js recommends that library projects have "type": "module" in their package.json. If you are generating UMD, Vite now defaults to adding a .cjs extension to reinforce that it should be loaded with `require`.
- `@carbon/charts` and `@carbon/charts-react` generate UMD files but their extensions where .js. Because their package.json files had "type": "module", Webpack assumed these to be ES modules - not UMD.
- This change makes the UMD bundles for both packages end in .cjs so Webpack recognizes their format correctly. 
- Should close https://github.com/carbon-design-system/carbon-charts/issues/1856 but needs to be confirmed

fix(1856): add cjs to umd bundles and update package.json exports

---

packages/core/src/components/axes/ruler-binned.ts
packages/core/src/components/axes/ruler.ts
packages/core/src/components/essentials/tooltip.ts
packages/core/src/interfaces/components.ts

- updated handler for tooltip show event to extract the datum from the event details and pass it as an argument to the customHTML callback function if one was specified within the chart options
Close #1518
The raw data point/points provided to the chart is not what gets propagated to the tooltip's customHTML callback function. 
This PR tries to address that issue by providing the "datum" associated with the hovered element as an argument to the `customHTML` callback, however, this solution still does not propagate the _raw_ data point/points passed to the chart as certain charts will modify the datum with extraneous properties.
This solution was chosen due to its unobtrusiveness rather than its preciseness. Ideally, the _raw_ data would be passed as an argument to the `customHTML` …

feat(tooltip): pass datum to customHTML callback function

---

packages/core/src/components/graphs/treemap.ts
packages/docs/src/lib/treemap/index.ts

- updated treemap chart to set the background color in data for the leaf text node so it can be referenced when determining the text color
Fix #1880
https://github.com/user-attachments/assets/296a09aa-3085-4e9f-a07a-24308498f0d1

fix(treemap): assign leaf text color based on custom colors

---

.github/workflows/release.yml
packages/angular/package.json
packages/core/package.json
packages/react/package.json
yarn.lock

- Remove auth-token from actions/setup-node@v4 in release workflow
- Set env variable NODE_AUTH_TOKEN to secrets.NPM_TOKEN for `npx lerna publish`
- Bump concurrently dependency

fix(release): remove auth-token from actions/setup-node@v4 and use env for publish

---

packages/core/scss/components/_axis.scss
packages/core/src/components/axes/axis.ts

* adds css-classes to ticks to make them more accessible from outside
- issues #1896

refactor(axis): use css-classes instead of style

---

packages/react/package.json
packages/react/vite.config.ts

Exclude react/jsx-runtime from the final bundle.  This should be excluded to allow users to update to React v19.
Including this dependency in the bundle results in 
`"TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')"`
fixes #1927

fix: exclude jsx-runtime from bundle

---

packages/core/src/components/graphs/skeleton.ts

closes: https://github.com/carbon-design-system/carbon-charts/issues/1984
Added `role` as `presentation` for skeleton svgs of pie and donut chart

fix: add presentation role for pie n donut chart skeleton
